### ISSUE TITLE
Paging plugin : next and previous button

### ISSUE THREAD

**Issue by fabien-h** [javve/list.js#132]
How would you implement a next and previous button ? It would be a nice improvement to a nice plugin :)

**Comment by Mat-thieu** [comment]
Using jQuery, I found a rather disgusting way to fix this

    $('.btn-next').on('click', function(){
		var list = $('.pagination').find('li');
		$.each(list, function(position, element){
			if($(element).is('.active')){
				$(list[position+1]).trigger('click');
			}
		})

	})
	$('.btn-prev').on('click', function(){
		var list = $('.pagination').find('li');
		$.each(list, function(position, element){
			if($(element).is('.active')){
				$(list[position-1]).trigger('click');
			}
		})
	})

**Comment by partyka1** [comment]
Is this for real?

**Comment by elixirgraphics** [comment]
Was hoping the latest update would have had this added. Any chance of it coming in the next update?

**Comment by hifall** [comment]
Second this. This feature would be really useful.

**Comment by vikramksrm** [comment]
Hi Javve, superb work on the plugin. 
But, 
this is basic requirement !!! companies will have some standards regarding Branding.

**Comment by synsa** [comment]
This feature is almost a requirement for most pagination plugins. 

It would be nice to have a solution implemented in order to display  prev/next buttons along with the default page numbers. ( << 1 2 3 4 5 >>)

Would love to hear any sort of update on this feature.

**Comment by eduardo-haddad** [comment]
adaptation of @Mat-thieu's code so that clicking "next" on last item returns to the first (the same for "prev"):

```
$('.btn-next').on('click', function(){
    var list = $('.pagination').find('li');
    $.each(list, function(position, element){
        if($(element).is('.active')){

            $(list[position+1]).trigger('click');

            if(!$(list[position+1]).length) {
            	$(list[position - (list.length-1)]).trigger('click');
            }
        }
    })

	})
	$('.btn-prev').on('click', function(){
	    var list = $('.pagination').find('li');
	    $.each(list, function(position, element){
	        if($(element).is('.active')){

	            $(list[position-1]).trigger('click');

	            if(!$(list[position-1]).length) {
            		$(list[position + (list.length-1)]).trigger('click');
           		}

	        }
	    })
	})
```

**Comment by Mat-thieu** [comment]
@eduardo-haddad The abomination is evolving :) Good addition
