### ISSUE TITLE
200 item max in the autoindexing?

### ISSUE THREAD

**Issue by albertbuchard** [javve/list.js#153]
Hi I am having trouble with the new list constructor when the list already exist it only store the first 200 items... is it possible to store more?

**Comment by jtnix** [comment]
@jsalamin  there is a new settings option non-intuitively named 'page' that is now auto default to 200.  Set this page to the upper limit you think you will need in the options json blob when you initialize a List.

Recommend the author clearly note this several places in the documentation and rename the setting to something more intuitive like maxPageItems or pageItemLimit or something more accurately describing what the setting actually does.

**Comment by javve** [comment]
:+1: 
I'll give the name and default setting a thought!

**Comment by chand3040** [comment]
Hi there,
Is there any functionality for lazy loading of Json data where we could have images and can loaded on demand?

**Comment by javve** [comment]
@chand3040 Nja, not really! But you can implement it yourself and use the `.add()` method.

**Comment by chand3040** [comment]
@javve  Thanks for the reply.
But I was looking if that could be available as a functionality.
Anyways thanks for the reply.

**Comment by hynese** [comment]
Hi folks,

Thank you for these comments.

```
           var options = {
              valueNames: ['day','date','location'],
              plugins: [ ListFuzzySearch() ],
              page:1000
            };
            var userList = new List('list-js',options);
```

By setting the "page" option to 1000, I was able to do everything I need.

I would hate for my list to grow and not realise this! Might this 200 limit be made more explicit?
