### ISSUE TITLE
Empty values sorted incorrectly

### ISSUE THREAD

**Issue by enlait** [javve/list.js#185]
There's a regression bug, the issue was fixed in alphanumeric sort https://github.com/javve/list.js/pull/136 but is present in natural sort algorithm used now. As a result, empty strings are always on top, whatever the sort direction.

The correct way would be not to do any string replacement at all if one of (or both) passed values are null/empty

**Comment by javve** [comment]
I've just created an issue where I reference all sort related problems. See #385. Thanks!
