### ISSUE TITLE
More advanced templating?

### ISSUE THREAD

**Issue by tlupfer** [javve/list.js#187]
I've run into a couple uses where I wanted to do some different things with templates. For instance, lazy loading images where the value goes into data-original instead of src. Or nested things where the inner class is wiped out by the outer class. Has anyone ever tried implementing a solution with Hogan or something similar?

**Comment by willthemoor** [comment]
> I´d also like to suggest that the markers are not only replaced on the first matching element but rather on all elements that are found.

> Right now single is true on the getByClass() method. Id suggest that this boolean is an option on plugin initialization.

I actually came here looking for a solution to this. I'd like to be able to use a data value like `name` as both the text content of the tag as well as to fill the value of an attribute like `data-name="{{name}}"`

    <li data-name="{{name}}">{{name}}</li>

**Comment by javve** [comment]
This is supported since https://github.com/javve/list.js/blob/master/History.md#2016-02-27-v120 
Example: http://listjs.com/docs/#example-6
