### ISSUE TITLE
Sorting by values of inputs

### ISSUE THREAD

**Issue by nderkach** [javve/list.js#190]
Hi,

first of all thanks for a great lib, man!

I can't seem to figure out how to order my items by the value of inputs in the list.
I.e. I have a list like:

``` html
<li>
  <span class="priority"> 1 </span>
  <input class="date" type="text" value="12-10-1945">
</li>
```

And then I have the following in my js initialisation:

``` javascript
window.onload = function() {
  var options = {
    valueNames: [ 'priority', 'date']
  };
  var userList = new List('panel', options);
};
```

And finally I trigger sorting with the buttons:

``` html
<a href="#" class="sort btn btn-default btn-sm" data-sort="priority">
  Sort by priority
</a>
<a href="#" class="sort btn btn-default btn-sm" data-sort="date">
  Sort by date
</a>
```

The first one (sort by priority works, whereas the second one doesn't.
Is there a way to sort by a particular attribute (input value in this case)?

**Comment by ooluwati** [comment]
Hi. Using the default sort function, any hidden items are automatically updated to visible once I type in the search bar. Is there an option to only sort on visible items or do I need to implement my own sortfunction ?
Thanks in advance.
