### ISSUE TITLE
Sort on multiple values

### ISSUE THREAD

**Issue by intelligence** [javve/list.js#193]
What's the best approach to sort on multiple values? I tried simply like this:
        `articleList.sort('title', { asc: true })
        articleList.sort('category', { asc: true })`

It behaves as it should in Safari and Firefox but in Chrome it doesn't..

**Comment by bjornmeansbear** [comment]
I have worked up a rudimentary example
http://codepen.io/bjornmeansbear/pen/RPywzN

it is able to loop through comma separated multiple "categories"

Hopefully this helps?
