### ISSUE TITLE
IE8 still not work in v1.0.1 :/

### ISSUE THREAD

**Issue by NewGuyUseGit** [javve/list.js#198]
Thank u so much for looking into this,but it seems still not work  :-(

----v1.0.1  existing list----
http://codepen.io/NewGuyUseGit/pen/zrmaA
http://codepen.io/NewGuyUseGit/full/zrmaA

----v1.0.2  fuzzy search----
http://codepen.io/NewGuyUseGit/pen/wzajt
http://codepen.io/NewGuyUseGit/full/wzajt

**Comment by gigerlin** [comment]
I have the same error at line 723 (val.valueOf()) with IE8. I tried downloading directly from the link provided above but it failed as well. I'm using list.js on Safari, Chrome and Firefox without problem. However I need to support IE8 as well... Any clue on this issue would be greatly appreciated.
Thank you!
