### ISSUE TITLE
Searching within groups of list elements

### ISSUE THREAD

**Issue by prashaantt** [javve/list.js#202]
An awesome library, thank you so much Jonny!

I've run into (what I think is a) slightly more complicated situation than what List seems to be designed for, and couldn't find anything in my searches so I thought I'd hit you up. https://github.com/javve/list.js/issues/59 came close but it isn't still what I'm looking for. Please excuse and feel free to summarily point me to the relevant discussion if this has been already dealt with.

Firstly, I'm not 100% clear what `items` in options is meant for, but I guess it's to specify the exact DOM element in which to tell List to find my stuff, right?

So I have this:

```
var listOptions = {
  valueNames: [ 'word' ],
  item: "<div class='row'><div class='col-sm-3'><li><a class='word'></a></li></div></div>"
}
```

You could guess I'm using Bootstrap to style my list. So my list elements are embedded in groups of `col` divs which are in turn held together in `row` divs, and there is quite a bit of this whole pattern getting repeated in my DOM, right from the `row` elements. The `div.row`s are direct children of `ul.list`.

In this setup, List seems to be indexing only the first element of each `col` div.

https://github.com/javve/list.js/blob/master/dist/list.js#L549 seems to suggest my use case may be supported with performance caveats, and indeed I could get the full list of elements under each `col` if I pass `single` as `true` at https://github.com/javve/list.js/blob/master/dist/list.js#L1215, but this doesn't seem to be fully supported yet and I'm naturally running into other issues if I do so. Am I doing something wrong or am I trying to stretch things too much beyond what I can expect List to reasonably support?

**Comment by alexcroox** [comment]
I thought the plugin works with divs as well as lists? So does it always have to be wrapped in <ul> even if you aren't using list (<li>) elements? My list is purely divs.

    <div class="list-container">
        <div class="item" />
        <div class="item" />
    </div>

**Comment by alexcroox** [comment]
Never mind, you can still use a div for the container it just has to have the class of `list` :)

**Comment by deltrotter** [comment]
Hi Alex

Any chance you could share your code - I am struggling to get it working with divs (I am using bootstrap). I have been playing with this example - works fine when I have it as standard lists, but not with Divs:

![screen shot 2015-07-25 at 14 45 34](https://cloud.githubusercontent.com/assets/13497256/8889658/cf785cb6-32db-11e5-8757-5443175b0109.png)


All help appreciated!

Cheers

Del
