### ISSUE TITLE
Update dists to work with the latest (2.1.0) version of RequireJS

### ISSUE THREAD

**Issue by gaurav-sanghani** [javve/list.js#208]
`dist/list.js` and `dist/list.min.js` seem to assume an older version of RequireJS that had different semantics for `define`. `List.js` itself is up-to-date and I simply ran `grunt dist` to generate the correct files. It's a minor change, as can be seen https://github.com/civitaslearning/list.js/compare/master...update-dists. This is especially important for using the library with bower.

**Comment by WillsB3** [comment]
+1 - still not working with the require js optimiser.

Using List.js 1.1.1 and grunt-contrib-requirejs 0.4.4 (which uses RequireJS ^2.1.0).

**Comment by earaya** [comment]
@javve seem like still not working? do you plan to fix this?

**Comment by valaxy** [comment]
@mattandrews, as WillsB3 said, the minified version list.min.js works fine with requirejs optimiser or common loader, I don't know why, but it works.

**Comment by javve** [comment]
v1.2.0 is now released and this should work now! Please tell me if not :disappointed_relieved: 
Release note: https://twitter.com/javve/status/705104547451170816 RT = :heart: :grin:

**Comment by mattandrews** [comment]
Thanks for the fix – it's been a long time since I tried to use this library though and I've since changed jobs and finished the project I was trying to use it with, so can't tell you if it works any more... but thanks!
