### ISSUE TITLE
sorting alphanumeric lists

### ISSUE THREAD

**Issue by ghost** [javve/list.js#215]
When a list contains entries beginning with a number or a letter, the "words" starting with numbers are sorted separately from the words with a letter. For example, a list containing the entries 1, 2, 3, a, b, c, would be sorted ascending like this

1 2 3 a b c

and descending like this

3 2 1 c b a

I would have expected the descending to be

c b a 3 2 1

Is there a way to sort it the way I was expecting?

**Comment by tvkarambelas** [comment]
Hi there,

Could you provide some more direction around how to implement a custom sorting function? I'm looking for the same functionality that @boreal suggested.

Thank you,
