### ISSUE TITLE
Can we separate the search input field from the list container?

### ISSUE THREAD

**Issue by elliottd** [javve/list.js#216]
If I move the search input field outside the list container, the search function fails to work. See an example here http://cdpn.io/zpuKF. (This is a small modification from the example on the list.js examples page.)

Is there a technical restriction that requires the input field to be in the same container as the list, or could we workaround this problem?

**Comment by WonderingDane** [comment]
@javve Your example doesn't seem to work anymore?

**Comment by afilina** [comment]
`i.search is not a function`

**Comment by f-monsa** [comment]
@WonderingDane this worked for me 

var options = {
  valueNames: [ 'name', 'born' ],
  searchClass: "search"
};

var userList = new List('users', options);

var searchField = userList.**utils**.getByClass(document, 'search', true);

userList.**utils.events**.bind(searchField, 'keyup', function(e) {
  var target = e.target || e.srcElement; // IE have srcElement
  userList.search(target.value);
 });
