### ISSUE TITLE
Doesn't sort dates properly

### ISSUE THREAD

**Issue by danieljameswilliams** [javve/list.js#221]
Is there a possibility to sort a field like a date, i can't seem to find any documentation about this, When sorted like text, the sorting is correct, but it should be like the screenshot here for it to work properly: http://screencast.com/t/frJQMHa5

**Comment by hynese** [comment]
Thank you for this tip. It saved me a lot of time. All I had to do was add a hidden input:

`<td class="s_date"><input type="hidden" val="1427716800" />30/03/2015</td>`

**Comment by zeamedia** [comment]
Why adding a hidden field? You could add a data-attribute like:

**js**
`valueNames: ['date', { name: 'timestamp', attr: 'data-timestamp' }`

**html**
`<td class="date timestamp" data-timestamp="1427713871">30/03/2015</td>`

Now you are able to sort via timestamp.
