### ISSUE TITLE
Issue sorting list of timestamps

### ISSUE THREAD

**Issue by activelogic** [javve/list.js#229]
JSfiddle Example: http://jsfiddle.net/2mU8k/2/

```
    var options = {
        valueNames: ['starttime'],
        sortClass: "list-sort",
        page: 50
    };

    var list = new List("js-list", options);
    list.sort('starttime', {
        order: "desc"
    });
```

I am experiencing an issue where when clicking multiple times on the Date header in the example to sort, the list soon becomes completely mixed up and incorrectly sorted.

In a normal situation this list is a few hundred elements long in my app and only requires a few clicks on the header to get the list to be incorrectly sorted.  In the JSFiddle example provided it takes a few more clicks to reproduce or a sequence of fast clicks.

I suspect this is related to the sorting algorithm being fired multiple times on the same list before a sort is completed, but not sure how to fix.

Any ideas on how this can be fixed?

**Comment by javve** [comment]
This sounds really weird an must be some weirdness in the browser. I'll close this issue now and please tell me if it's still a problem in the latest Chrome and I'll open it.

...and I'll put a reference to #385 here as well.
