### ISSUE TITLE
Search box clears when filtering thru Ajax data

### ISSUE THREAD

**Issue by lenichols** [javve/list.js#238]
I have an ajax call which pulls in json data stored in a mysql table. The "search" seems to work but for some reason it clears my ajax data when you type. Any ideas? Is this an issue that can be resolved with addn'l functionality? Works great when my values are hard coded into my table 'th's'... just can't seem to get it to work with my ajax data.

**Comment by javve** [comment]
You'll have to use List.js's own method `.add()` to add data to the list. You can't just add stuff to the DOM.
www.listjs.com/docs/list-api#add
