### ISSUE TITLE
Error: "ReferenceError: List is not defined" 

### ISSUE THREAD

**Issue by ArcTanSusan** [javve/list.js#243]
I have the listJS file in the script tag at the head tag of top of the html `tree.html` page. Then I have a `sortnotebooklist.js` referenced also in the script tag at the bottom of the page. The JS file is the following: 

```
var options = {
    valueNames: [ 'last_modified' ]
};

var notebook_items = new List('notebook_items', options);
```

I get the error on the browser console: 
`ReferenceError: List is not defined`

How do I fix this? Did I imported the library incorrectly? I've tried using both `<script src="http://listjs.com/no-cdn/list.js" type="text/javascript"></script>` and `<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js" />` in the `<head>` tag without success.

**Comment by KyleLauKC** [comment]
Try to rearrange the scripts codes.

```
<script type="text/javascript" src="js/list.min.js"></script>
<script type="text/javascript" src="js/your-own.js"></script>
```

**Comment by haasr** [comment]
I was working in Django and had this issue. Placing both script tags in the same template with list.js did the trick. Thanks!
