### ISSUE TITLE
Implement: Not found results

### ISSUE THREAD

**Issue by brunobatista** [javve/list.js#245]
Hi, very nice plugin, congrats!

Have any way to display a message when not have results?

**Comment by javve** [comment]
There you go: 
http://codepen.io/javve/pen/VYmWpX

**Comment by brunobatista** [comment]
Thanks @javve :+1:

**Comment by DanLaufer** [comment]
@javve Thanks so much for the effort on all of this. This no longer works. Is there a more recent version of "No Results Found"? Thanks.

**Comment by mgilberties** [comment]
@DanLaufer Try this: https://codepen.io/mgilberties/pen/EwELmm
