### ISSUE TITLE
Content jumping around - chrome error?

### ISSUE THREAD

**Issue by ghost** [javve/list.js#249]
Hello! i have experienced a problem. And i don't know how to solve it. 
I have been troubleshooting for a long time now, and i can't find any errors.

Here is a fiddly to my problem:
http://jsfiddle.net/Z6Ffp/

Click on the button:
"jyl (click me a lot, - i crash)"
And you will se how the list jumps around. It should work like the button:
"Lol (click me i am fine too)"

This problem happens in chrome, but not in IE. 
Any ideas?
oh and sorry for the DIV mess in there. 

Thanks a lot.

**Comment by javve** [comment]
This seems like it was some weird browser bug. Works fine for me now.
