### ISSUE TITLE
The list sorters don't seem to work well with hidden columns or multiple tbody elements in a table

### ISSUE THREAD

**Issue by roddines** [javve/list.js#250]
The list sorters don't seem to work well with:

1. hidden columns
2. multiple tbody elements in a table (used when you have grouped rows)
3. a lack of a good table example on your web site.
4. please make it work better with Twitter's Bootstrap 3.0 buttons

Just letting you know know the problems we are facing.

**Comment by javve** [comment]
Thanks for your input!

1. How do you hide them?
2. That is not supported. However, you could initiate one instance of List.js for each tbody and then make a custom search function that searches them all.
3. http://www.listjs.com/examples/table
4. In what way?
