### ISSUE TITLE
Arrows next to column headers

### ISSUE THREAD

**Issue by thevarunshah** [javve/list.js#252]
For sorting HTML tables, is there a way to add up/down arrows next to the column headers when they are clicked? It's a minor UI change but it helps keep track of which column is being sorted and in which direction.

Thank you in advance.

**Comment by thenatsky** [comment]
If you're using bootstrap (or not) you could use glyphs for this.  This is my css:

```
table.sortable .sort:before {
	font-family: FontAwesome;
	font-size: 0.75em;
	color: #333;
	font-weight: lighter;
	content: "\f0dc";
	padding-right: 0.7em;
}

table.sortable .sort.asc:before {
	content: "\f0de";
}

table.sortable .sort.desc:before {
	content: "\f0dd";
}
```

and this is an example `<th>` in my markup:

`<th class="sort sort-control" data-target="list" data-sort="column_name" role="button">Column Name</th>
`

Note: I added the role="button" so I get the pointer when using a mouse taken care by bootstrap, but if you're not using bootstrap, then it's just a matter of adding "cursor: pointer;" to the css.
