### ISSUE TITLE
Feature request: Table sorting when cells have rowspan>1

### ISSUE THREAD

**Issue by 0xadri** [javve/list.js#257]
When trying to sort a table that has a rowspan superior to 1, the whole thing falls apart.

See the difference between http://jsfiddle.net/59Z4G/ and http://jsfiddle.net/d7fJs/

Is there a way to make this work?
Or is a fix/new-feature required in the library?

Thanks

**Comment by mtekman** [comment]
I've placed a possible workaround here:
https://github.com/javve/list.js/issues/377
