### ISSUE TITLE
Adding input elements to a list

### ISSUE THREAD

**Issue by jeresiv** [javve/list.js#258]
I would like to filter over a list of checkboxes that are dynamically added via an ajax request. Is there way to use list.add to set the value attribute of the checkbox input element?

    listObj.add( { id: 10 });

    <input class='id' type='checkbox' name='checkbox_list' value='10' />

**Comment by javve** [comment]
I've added complete support (your solution as well as the existing image solution is not complete) for more elements to the [TODO](https://github.com/javve/list.js#todo) and will include that in a coming release.
