### ISSUE TITLE
animating list items being hidden/revealed

### ISSUE THREAD

**Issue by FND** [javve/list.js#264]
After quite some time digging into List.js's source, I seem to have found a way to add animations when list items are removed/added:

http://codepen.io/anon/pen/KAadF

```javascript
var templater = userList.templater;
templater.clear = jQuery.noop; // relying on `show`/`hide` instead
templater.show = function(item) {
  jQuery(item.elm).slideDown();
};
templater.hide = function(item) {
  jQuery(item.elm).slideUp();
};
```

However, I'm not sure that's the Right Way™; it feels like a workaround - is there a better way?

(By the way, I was surprised that List.js's default templater erases the list and recreates it from scratch - is there a reason for that?)

**Comment by megalofauna** [comment]
michaltowilk,

This is what I've been *unsuccessfully* trying as well. Would you mind going into a bit more specific detail? Maybe post your relevant code?

**Comment by javve** [comment]
I'll close this now since it's more a of a question than an issue.
