### ISSUE TITLE
debouncing search queries

### ISSUE THREAD

**Issue by FND** [javve/list.js#265]
After figuring out animations in #264, I realized that search queries need to be debounced (i.e. postponed to avoid repeat triggering within a short timeframe). This was previously mentioned in #53, but ended up not being integrated (not quite sure why).

Normally I'd just use a simple helper [like this](https://github.com/bengillies/stuff-js/blob/3a0a8bfcde36af8114ea55c06935c6fd8711bc2c/src/fp.js#L68-82) to adjust this within my application:

```javascript
list.search = debounce(list.search, 100);
```

However, List.js's `searchMethod` and its invocation are inaccessible from the outside, leaving me pretty much impotent:
https://github.com/javve/list.js/blob/f17ba5d4fca868b795f3cc3bd0514a47787f566e/src/search.js#L74
https://github.com/javve/list.js/blob/f17ba5d4fca868b795f3cc3bd0514a47787f566e/src/search.js#L101

Would it be worth adding debouncing to List.js's core - if not, could we make `searchMethod` customizable?

**Comment by javve** [comment]
Closed -> https://github.com/javve/list.js/pull/267#issuecomment-133880432
