### ISSUE TITLE
indexAsyn referenceError

### ISSUE THREAD

**Issue by mblanco0626** [javve/list.js#268]
Hello,
 When using the indexAsync option I get a referenceError init is not defined inside of the parseAsync function

**Comment by wolffe** [comment]
+1 I get the same error.

**Comment by julone7** [comment]
hi, do you have any news here ?

**Comment by javve** [comment]
v1.2.0 is now released and this should work now! Please tell me if not :cold_sweat: 
Release note: https://twitter.com/javve/status/705104547451170816
