### ISSUE TITLE
Search Page with fliters and list

### ISSUE THREAD

**Issue by blpraveen** [javve/list.js#270]
Hi 
We have a travel portal justtrip1.com. we are currently using simple scripts to show the results on the search page. We have performance issue as the page takes long time to load when there are 1000's of search result data. I am trying to fix this issue by using pagination and pipeline(Similar to DataTables). How can I achieve this using listjs. Please advice or usefull information is helpful

**Comment by javve** [comment]
Great advise @j-ro!
The main problem is that the DOM is slow. You don't want to have thousands of items on the site. That's why using @j-ro's advice + the [pagination plugin](http://www.listjs.com/docs/plugins/pagination) should be a good solution for you.
