### ISSUE TITLE
listObj.values() returns dirty strings

### ISSUE THREAD

**Issue by pioneerskies** [javve/list.js#273]
Hi there and thanks for the piece of code, really appreciated.

I've noticed a possible problem:

```haml
%li
  %p.type= $title[1]
```
My variable `$title[1]` is var_dump-ed as:
```
string(3) "igs"
```

The library reads it as

```javascript
item.values().type
"
  igs
"
```

so I have to trim the value before to use it inside, e.g., a `filter` method.

Am I doing something wrong?

Thanks and goodbye

**Comment by javve** [comment]
List.js fetches the value from the element like this:
`values[valueNames[i]] = elm ? elm.innerHTML : "";`

So the dirty string seems to be due to the html in some way.

**Comment by pioneerskies** [comment]
That's ok. Thanks for taking the time to check.
