### ISSUE TITLE
Re-ordering table following AJAX update

### ISSUE THREAD

**Issue by gjcourtney** [javve/list.js#274]
I have table with list.js working on them, with multiple columns that they can be ordered by. The tables are periodically updated via an AJAX call (it's a check-in/check-out system for people), but when you re-order the table following an AJAX update, the data in each row defaults back to the values from when the page was first created.

Essentially, when re-ordering, any data that has been updated via AJAX is lost until AJAX polls again and re-updates the table.

Seems like list.js is caching the data in the table rather than using the data present at the point of ordering...

**Comment by niknah** [comment]
You have to go through the list.items[] array
and load the new values into each item via item.values()

This worked for me.

**Comment by javve** [comment]
In next version there'll be a feature that allows you to re-index the list.

**Comment by javve** [comment]
v1.2.0 is now released and the .reIndex() method should solve this: http://www.listjs.com/docs/list-api#reindex

**Comment by itsazzad** [comment]
Not updating with reIndex.

Data was populating through ajax.
I clicked to sort and it was sorted.
But the rows were not sorting automatically on subsequent ajax responses.
