### ISSUE TITLE
Filtering "cloned" lists on one page doesn't work

### ISSUE THREAD

**Issue by tobi-w** [javve/list.js#276]
Hello,

I know list.js does not support flitering nested lists. That is why I feel the possibility to filter "cloned" lists with the same filter would already increase its usabilty tremendously.

What I am trying to achieve: place multiple "cloned" lists on one page and have a filter button which will filter the <li> elements in all lists (the lists are built identically).

Even though list.js looks for the ul class (e.g. .list) within the defined div it only applies the filter to the first list - not all lists with that same class.

Here a fiddle to demonstrate the problem: 
http://jsfiddle.net/5mz5kefy/

When clicking the "Swedish" filter it filters the Sweden entries in the first list - not all three. 

How can we achieve this?

Please forgive me if that is straight forward - I am new to jquery and have spent many hours trying to make progress.

Thank you for your help
Tobais

**Comment by javve** [comment]
You'll have to create three separate List.js instances. Your solution won't work.
