### ISSUE TITLE
Intentionally return only empty values?

### ISSUE THREAD

**Issue by jcwatson11** [javve/list.js#278]
Is there a way to intentionally return only the empty values in a column?

I'm using list.js to sort/filter a table with english translations on the left, and a target language translation on the right. It would be really helpful if I could make a checkbox that filters out all the work you've already done and only presents the rows that don't have a target translation yet. I was thinking I could attach an event to the checkbox to do this with something like:

    listObj.search('',['targettranslation']);

But alas. It does not work. It treats the empty string as if it should return all results.

Is there a way to intentionally filter for empty values?

**Comment by javve** [comment]
Sounds like something that could be solved with filters -> http://www.listjs.com/docs/list-api#filter

**Comment by jcwatson11** [comment]
Yep. Looks like it. Thanks!
