### ISSUE TITLE
on sortComplete not working

### ISSUE THREAD

**Issue by MoiseScalzo** [javve/list.js#280]
Hello, realy nice plugin but I need to call a function after sort list is complete but seems doesn't working.
my code:

<pre>
usersList = new List( 'users', options, values );
usersList.on('sortComplete', function(){
            alert('done');
});
</pre>

maybe I'm doing something wrong?
thank you in advance
Moise

**Comment by javve** [comment]
Hmm it should work. Can't say more without more example code.

Tests work:
https://github.com/javve/list.js/blob/master/test/test.on.js#L98

**Comment by max-schu** [comment]
none of the callback are working for me either.
please consider reopening the issue and have a look into it.

`
	var options = {
		valueNames: [
			'price', 
			{ data: ['collection'] },
			{ data: ['category'] },
			{ data: ['collection_order'] }
		]
	};
	var el = document.getElementById('shop');

	var itemslist = new List(el, options);`

itemslist.on('sortComplete', function(){
			alert('sorted!');
		})
