### ISSUE TITLE
dl element

### ISSUE THREAD

**Issue by a-x-** [javve/list.js#282]
Hi!

Can it working with dl element?

```html
<section class="faq">
  <input class="search" type="search" />

  <section class="section-list">
    <dl class="list">
      <dt class="term">Term 1</dt><dd class="def">Def 1</dd>
      <dt class="term">Term 2</dt><dd class="def">Def 2</dd>
      <dt class="term">Term 3</dt><dd class="def">Def 3</dd>
    </dl>
  </section>
</section>
```

----

Something like this?

```js
var list = new List('faq', {valueNames:['term', 'def']});
```

**Comment by javve** [comment]
Hm, no sorry. List.js requires a single item root element :cry:
In a `dl`list there is two (both a `dt` and a `dd`).

I haven´t thought about the `dl` case actually. But due to core features of List.js this case will not be supported.
