### ISSUE TITLE
Descending sort with custom sort function not working ?

### ISSUE THREAD

**Issue by sterfield** [javve/list.js#283]
Hi,

I'm trying to create a custom sort function, in order to sort a complex column, full of string information.

The column is displaying some string info, with a percent, something like this: `azf(80%)`.
I want to sort on the percent, so I need to extract the value from the string, and sort it.

I've done something similar to this : http://jsfiddle.net/sterfield/zhcmbp4b/6/

As you can see, there's three values in percent in the table, and if you click on the header "%", it will sort the table based on the percentage, and not on the string before the percentage (which would be the case if using the naturalSort).

So far so good.

Except that, if I explicitely ask for a "descending" sort, I only obtain an ascending sort. You can change the value "order" in the dictionary to "asc", you'll obtain the same result.

So, is there an issue with the descending sort for custom sort functions ? Or did I do something totally stupid ?

Thanks for your help.

Sterfield

**Comment by javve** [comment]
Making list.js be responsible for desc/asc is great suggestion! I'll add it in the next release! :beers: :grin:

**Comment by javve** [comment]
Ref https://github.com/javve/list.js/commit/81d1148489c99b8503e725805c2a6ce2bde47b11
