### ISSUE TITLE
Reset list on button click

### ISSUE THREAD

**Issue by jjkilpatrick** [javve/list.js#285]
Hi,

Is there anyway of clearing the search box and resetting the list on click of a button? 

Thanks

**Comment by javve** [comment]
Sure!
```javascript
$('#reset-button-id').click(function() {
   $('#search-field').val('');
   listObj.search();
});
```

**Comment by mayeenulislam** [comment]
Reset listing as mentioned above worked like a charm.
If I type something on the search box, and then clicking the reset button, it works.

But it's not working, if the <kbd>Sort by Name</kbd>-like button is implemented.
If I click on the sort button once, and then clicking the reset button removes the `.asc` class from the sorting button, but the list remains sorted. It doesn't reset.

Please note that, I've a list with hierarchy, that's not actually `ASC` or `DESC` ordered, it's ordered by **hierarchy**. I tried the following, but as you know [`false` doesn't mean default, it means `DESC`](http://www.listjs.com/docs/list-api#sort):

      $('#reset-button-id').click(function() {
            $('#search-field').val('');
            listObj.search();
            listObj.sort('name', { order: false });
      });

So, it's not working as expected. I also tried `listObj.sort();`, that's a shit try, you know. :)

**Comment by javve** [comment]
There are currently no way to reset list to original sorting. I'll look into that before next version (1.3.0 not 1.2.0)

**Comment by jeffdbeats** [comment]
I had a similar problem, this worked for me....

$("#reset-button-id).on('click', function(){
	userList.filter();
});

(Make sure to change userList to match your list name)
var userList = new List('users', options);

**Comment by jeffdbeats** [comment]
Thank you this helped me!

**Comment by JayHoltslander** [comment]
````js
$('#reset-button-id').click(function() {
   $('#search-field').val('');
   listObj.search();
});
````
That code causes my page to refresh (unlike manually clearing the input). Hmm
