### ISSUE TITLE
Message after NO RESULTS FOUND

### ISSUE THREAD

**Issue by manlioma** [javve/list.js#289]
Is it possible to show a message if I search something that isn't in a list ?
Thank you !

**Comment by javve** [comment]
Sure! Use something like this. Here is an example: http://codepen.io/javve/pen/VYmWpX

**Comment by DanLaufer** [comment]
This no longer works....Is there a more-recent version of "no results found"?

**Comment by mikevaux** [comment]
Hi @DanLaufer ,

Currently none of the Codepens for List JS are actually functional, but the concept of checking the `matchingItems` length on `updated` is sound. I've just used an application of it and it worked fine.

Hope that helps?

**Comment by mikejanssen** [comment]
It's working for me if I swap in the new CDNJS info — `<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>`
