### ISSUE TITLE
Way to exclude elements from sorting.

### ISSUE THREAD

**Issue by andreyvolokitin** [javve/list.js#295]
I did not find a way to pass specific set of elements to be sorted by list.js. It only possible to pass whole element and all its children then will be sorted. But what if we need to sort only some elements and exclude others? 

It is sounds uncommon but if we have a table with two headers - horizontal end vertical, and we want to sort table columns by certain row (as opposed to common patter of sorting rows by column) - we actually need to sort all cells in the row but the header-cell (th), and with list.js it seems that there is no way to do that because we simply can not exclude this header-cell from sorting.

**Comment by javve** [comment]
I'm sorry but it is not possible to exclude things from being sorted that is within the list-container (e.g. `<tbody class="list">`)
