### ISSUE TITLE
How does it cater a large amount of data

### ISSUE THREAD

**Issue by jjhesk** [javve/list.js#296]
Lets say that I have alot of data to display and I want to display them according to my attention need.
Does it happen if u can make it a view on each item for example a backaground in jpg, and some custom data like title, date, author, metadata1, metadata2, metadata3, interactive data responding to the current search on each single view. I have another solution from https://datatables.net/. but this thing is just too traditional and nothing come to make things based on importance but I deeply believe that people and more people really like to look into waterfall, 3 or 2 columns to show down whats important and whats not. Having a list view is nice but what if it can switch dynamically into a nice waterfall view and have it to snap horizontal and vertical of its view presentation. That will be nice!

**Comment by javve** [comment]
Thanks a lot for your suggestion!

However, I think that most of the features you describe sound more like things for a developer to implement around List.js rather than include it in the core.
