### ISSUE TITLE
Conflict with Typeahead.js

### ISSUE THREAD

**Issue by hjbolide** [javve/list.js#297]
Currently I am using list.js master with typeahead.js master together, and some thing funny happened:

The basic layout is fairly simple:
A big table with multiple cells in each row, some cells are readonly text while some cells are editable input elements.

The event binding order I have is: 

1. Bind typeahead:selected event to my input elements
2. Create List on the whole table with filtering available; filtering will happen not only on readonly text cells but also input element cells.

The problem then happens, the reason being is, in templater.js section, the set method actually overrides the innerHTML of the td element, that wipes out all pre-existing events I have tried to bind to the element.

The easy solution is to adjust the ordering so typeahead binding happens after creating list.

I'm not sure if this is an issue, or my understanding of list.js is completely wrong, which leads to mis-use of list.js in a not recommended scenario.

If anyone could kindly point out the best practice, that would be very awesome.

Thanks,
hjbolide

**Comment by javve** [comment]
I'm not sure that there is a good idea to use List.js with Typeahead. That will most likely lead to weird problems.

If you still have issues with Typeahead + List.js, try StackOverflow for help. Good luck!
