### ISSUE TITLE
Re-initialization

### ISSUE THREAD

**Issue by richman64** [javve/list.js#298]
Hi, I'm using List.js on a table and with other javascript code, I'm removing an entire table row from one table and adding it to another (sort of like your traditional << Left  Right >> mover) but both tables have the sortable/searchable list function.  This dynamic move does not reset the list contents, so after the move if you sort or search, the items go back... so I re-initialized both tables after the move using new List(id, options) again and it works, but then the column sort buttons double fire from dual inits (preventing them from working properly).  Is there a method of re-initialization of an existing list so it can pick up any dynamic adds that didn't use the add / remove methods within your library?

I'm not able to use List.js add/removes because the table is in a form and some of the required form elements cannot be recreated or duplicated for the new table row.  I need to keep using my existing add/remove but reinitialize the list without double initializing the sort buttons.

Thanks to anyone who can help!

Fiddle for clarification: http://jsfiddle.net/richman64/nywpd5md/8/

**Comment by javve** [comment]
I've added a reIndex feature that will be included in the next release!

**Comment by javve** [comment]
v1.2.0 is now released and the reindex() method should solve your problem: http://www.listjs.com/docs/list-api#reindex
