### ISSUE TITLE
Option for not taking into account accented characters

### ISSUE THREAD

**Issue by larmarange** [javve/list.js#300]
Would it be possible to have an option (both for normal search and fuzzysearch) for removing accents before searching, i.e. searching "lé" will detect "Lea"?

Best regards

**Comment by gasyoun** [comment]
What would be the full list. é=ea is the full list?

**Comment by larmarange** [comment]
More generally, the option will be to allow a accent-insensitive search. It's a common problem with all search system with non-English languages.

Full list of accents depends on languages. However, some list of accents could be found at:

http://stackoverflow.com/questions/990904/javascript-remove-accents-diacritics-in-strings

or 

http://stackoverflow.com/questions/21833584/jquery-datatables-accent-insensitive-alphabetization-and-searching

**Comment by Glideh** [comment]
I agree, diacritic insensitive search would be useful

**Comment by davidlesieur** [comment]
https://github.com/dundalek/latinize seems to have a good conversion map.

**Comment by javve** [comment]
I'm closing all unicode errors with a reference to #385 :wave:

**Comment by tdbs** [comment]
I can't see why this was closed #385 is about sorting order not about ignoring accented characters!
