### ISSUE TITLE
Wanting to hide the list and just show the search box

### ISSUE THREAD

**Issue by mizcozma** [javve/list.js#305]
Hi there

This is the closest thing to what I have been looking for. 
I have a long list of neighborhoods in a city, people will look for their city to see what zone it is in...
So I want to hide the list, and have a search box that they can start typing their neighborhood, and it would figure out what they were typing and post that neighborhood.

http://www.listjs.com/examples/pagination   this one comes the closest.

But I would really want just a search box, with a hidden list, and when their neighborhood is selected they see what zone it is in. 

any chance i could do this.. and if so how :)

Thanks

**Comment by javve** [comment]
One way would be to do something like this: http://codepen.io/javve/pen/YyqyRg
