### ISSUE TITLE
Add option to have empty results on beginning

### ISSUE THREAD

**Issue by igorspasic** [javve/list.js#308]
Initially, when search field is empty, some results are shown (?) Add option to show results only when user entered > X keys (like 2 or more)

**Comment by javve** [comment]
This is not an option I intend to implement. But you an do something like this to achieve the same thing:

```javascript
list = new List(...)
$(list.list).hide()
list.on('updated', function(list) {
  if (list.searched) {
    $(list.list).show();
  } else {
    $(list.list).hide();
  }
});
```

**Comment by igorspasic** [comment]
Yeah. Just an idea: list.js may be used not only for filtering existing content, but for searching the site. ive just made a filter/plugin for [nanoc](http://nanoc.ws/) on one of my projects ([jodd](http://jodd.org)); had to patch the lists code to support links (see my other issue). anyway, i believe that there is nice potential in list.js and therefore having more options may give people ways to use it on more places :) Thank you!

**Comment by naimhiq** [comment]
Hi guys, 

Do you know how can I set to display a message if the user for instance searched for the keyword that doesn't not exist in the list, by default listjs is giving empy  and not showing any message like "no match data.  

Thanks for your help !
