### ISSUE TITLE
Character limit on items?

### ISSUE THREAD

**Issue by dpaanlka** [javve/list.js#311]
Hello,
I’ve been using List.js for a few months and it’s been working great. My project only has 16 or so items in my list, for example one of my list items is as follows:

```html
<li>
	<div>Sealants</div>
	<div>fissure caries cavities prevention preventive preventative pits pedo pediatrics sizzurp</div>
</li>
```

The first div is visible in the list and my second div is invisible and contains related keywords that a user might search. The system seems to have been working pretty well until today I noticed that towards the end of the hidden div none of those words trigger results with List.js

So for example if someone searches for “sealants” or “cavities” they get a hit, but not “pedo” or “sizzurp”

I hope I’m explaining this well. Is there any obvious reason this might be happening? Like a character limit of some sort? I have fuzzy search plugin installed and working fine (except for the above limit).

Thanks!

**Comment by dpaanlka** [comment]
I’ve forked one of the List.js samples in CodePen and created an example of my bug:

http://codepen.io/dpaanlka/pen/EaoNmV

Typing “sizzurp” has no results.

**Comment by javve** [comment]
This is a limitation is the fuzzy search due to performance reasons. Ref: https://github.com/javve/list.fuzzysearch.js/issues/8
