### ISSUE TITLE
Max list length set to 200 items

### ISSUE THREAD

**Issue by miguelcb84** [javve/list.js#317]
I'm using this awesome lib in a **import contacts** from gmail feature, and in that case users have plenty of emails (items in the list)

In my case, it turns out that the email list is cut off in the 200th email while there were more than 700 emails before using the lib.

Is the max length of the list set on purpose? is there any way to remove this limitation?

**Comment by luxe** [comment]
@miguelcb84 similar issue.  How did you solve it?

**Comment by miguelcb84** [comment]
Sorry, I didn't read this till now. I used the option `page` and set it to a higher value. Actually, I just checked the repo, and the default if shifted from 200 to 10000, this this should not be a problem any more with lists shorter than that length.
