### ISSUE TITLE
Support for jquery ui draggable, dropable and selectable.

### ISSUE THREAD

**Issue by rpokrovskij** [javve/list.js#318]
I'm using listjs on unordered list (ul) together with paging plugin and jquery ui draggable/droppable/selectable. I am able to drag items out from the list to another area (after DnD operation I call List API remove) , but then I've fallen into ambushes.

1) situation: first we initialize listjs with paging plugin , then draggagble; therefore only first page items will be catched by draggable. Therefore when I remove items from the lists - new items "arrive" to the current page  and I need to include them into draggable (the same I should do when I move to another page)  but  I can't find how I could catch "shown first time" event.
It can be solved initializing draggable/selectable first, but then we will meet the same problem again when we  drop items to the listjs - lets say we add them using lisjs add - how to initialize them when they arrive on the page?   

2) What is also missed: it seems the "add" method doesn't work for me. By drop operation I would like  to include  the same <li> that were dragged, and not recreate them with List.Add(anonymous_object) from template. They are quite complex, have html5 data, and data in other attributes, it seems templates doesn't cover such situations. What I'm searhching for: Add should accept jquery selector (and/or html text) and include items as they are (parsing them for values of course).  May be it is allready implemented and I just can't find...

3) how to get listjs item API from $('li')? I would like to experiment with item's hide and show but it seems there are only one way: loop through items array.

**Comment by javve** [comment]
I'm sorry but this is to much of a special case for me to take it in account for the core lib. List.js is very dependent on where the items are in the DOM and adding other libs such as draggable & droppable will most likely mess up a lot of stuff for List.js.
