### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ReservedDeveloper** [javve/list.js#319]
Hi,

I was wondering when we might see the next release tagged for this library? I've seen several comments on outstanding issues all indicating they'll be resolved in the next release. Most of those were around this time last year. At first I thought perhaps the library had been abandoned, but I still see commit activity. But the last release was quite some time ago!

Could we get a new release tagged?

**Comment by wolffe** [comment]
+1

**Comment by gambolputty** [comment]
:+1:

**Comment by javve** [comment]
It's getting closer! --> https://github.com/javve/list.js/tree/1.2.0

**Comment by javve** [comment]
I'm sorry for being crazy bad at taking care of this lib :cry:
