### ISSUE TITLE
option to latinise while searching?

### ISSUE THREAD

**Issue by wolfheart** [javve/list.js#321]
It would be cool, if there would be an option to latinise the search string and the items to be searched in.
There is an Javascript snippet for latinising strings:
http://semplicewebsites.com/removing-accents-javascript
But there seems to be a problem with the unicodes in that JS file.
Here you can get a workaround using base64 coding:
http://stackoverflow.com/questions/990904/javascript-remove-accents-diacritics-in-strings#9667752

I tried to put it - hardcoded :-/ - into the fuzzysearch, but I'm not sure if this is the best approach:
```javascript
//~line 655:
    var fuzzySearch = {
        search: function(searchString, columns) {
            // latinise the text
            searchString = searchString.latinise();
//~line 681:
        values: function(values, value, searchArgument) {
            if (values.hasOwnProperty(value)) {
                var text = toString(values[value]).toLowerCase();
                // latinise the text
                text = text.latinise();
```

**Comment by davidlesieur** [comment]
This looks like a duplicate of #300.

**Comment by javve** [comment]
I'm closing all unicode errors with a reference to #385 :wave:
