### ISSUE TITLE
node+nw.js: cannot find module 'get-by-class'

### ISSUE THREAD

**Issue by hibiyasleep** [javve/list.js#326]
trying `require('list.js')` rising `MODULE_NOT_FOUND: cannot find module 'get-by-class'`.

I don't have any idea for this sub-require, so submiting this issue

**Comment by MarkLeMerise** [comment]
This is likely the same issue as #271. According to the author, this is a known issue, and will be addressed in the next version.

**Comment by hibiyasleep** [comment]
:+1:

**Comment by javve** [comment]
Yeah, it's a duplicate and it will be fixed in next version.
