### ISSUE TITLE
Clear the sorting

### ISSUE THREAD

**Issue by Leprosy** [javve/list.js#328]
First of all...excellent library! ...just one thing...Is there a way to reset the sorting(I mean...get the original, initial configuration of items)? I'm looking the API and doesn't seem to be a method to do that.

**Comment by Leprosy** [comment]
Anyone?

**Comment by javve** [comment]
You can't "go back" to the original sorting, sorry.

**Comment by cbier** [comment]
@javve I also need to do this. Is it still not possible to revert to the original ordering of things?

**Comment by eduo** [comment]
Is this still opened? I've worked around it by adding the original sorting as a data value and then having the "Reset" option always sort by ascending using this, but I'd much rather prefer a built-in function.
