### ISSUE TITLE
Search with no results breaks iOS

### ISSUE THREAD

**Issue by simonseddon** [javve/list.js#330]
Has this been tested on iOS? Searching for something which returns zero results ("-") on iOS breaks the script. Deleting the invalid search term and starting again, entering a valid search term, doesn't work.

Note, I'm using a very basic implementation of the script, searching two elements (valueNames), no sorting, with the pagination plugin if that helps debugging.

**Comment by simonseddon** [comment]
Update. The issue seems the same on Safari desktop, too.

**Comment by javve** [comment]
Hmm, when I test http://www.listjs.com/examples in Safari for both desktop and iOS everything works fine.

I think I need to test the implementation to find error :/
