### ISSUE TITLE
List.js failing to sort in Chrome

### ISSUE THREAD

**Issue by JasonEspin** [javve/list.js#331]
We have a list setup with the following markup. When selecting an option from the dropdown in Chrome, no sort occurs. All other browsers work correctly and sort the data based upon the option selected.

    <div id="search-results">
                Sort by: 
                <select>
                    <option data-sort="name" class="sort asc">Name</option>
                    <option data-sort="date" class="sort">Date</option>
                </select>
                <div class="list col-md-12">
                        <div class="package col-md-8">
                                <span class="name">Blue Lagoon swim</span><br>
                                <span class="difficulty">Easy</span><br>
                                <span class="date">02/11/2015</span>

                        </div>
                        <div class="package col-md-8">
                                <span class="name">Blue Lagoon swim</span><br>
                                <span class="difficulty">Easy</span><br>
                                <span class="date">03/11/2015</span>

                        </div>
                 </div>
    </div>

    <script type="text/javascript">
            var options = {
                     valueNames: ['name', 'date']
            };

            var userList = new List('search-results', options);
     </script>

**Comment by javve** [comment]
You can't use the automagical sort classes like that. It has to be buttons. You'll have to use the sort api i you want to have a sort function like that. http://www.listjs.com/docs/list-api#sort
