### ISSUE TITLE
Revisiting issue #285: Reset list on button click

### ISSUE THREAD

**Issue by lyellick** [javve/list.js#332]
Referring to this ticket on how to reset the list: https://github.com/javve/list.js/issues/285

When I added this little fix to my set up the search box would clear, but the lists itself wouldnt. Is there something else that might help with what i'm trying to accomplish?

**Comment by n00b3** [comment]
listObj.search() works for me in resetting the list. make sure to replace listObj  with whatever the name of your list is.
