### ISSUE TITLE
Do I need all these lines in the source code?

### ISSUE THREAD

**Issue by wolffe** [javve/list.js#333]
Do I need all these lines in the source code?

    require.alias("component-classes/index.js", "list.js/deps/classes/index.js");
    require.alias("component-classes/index.js", "classes/index.js");
    require.alias("component-indexof/index.js", "component-classes/deps/indexof/index.js");

    require.alias("segmentio-extend/index.js", "list.js/deps/extend/index.js");
    require.alias("segmentio-extend/index.js", "extend/index.js");

    require.alias("component-indexof/index.js", "list.js/deps/indexof/index.js");
    require.alias("component-indexof/index.js", "indexof/index.js");

    [...]

**Comment by wolffe** [comment]
Any thoughts on this? I'm using the minified version, but I think I could squeeze more of it by removing these unnecessary requires.

**Comment by javve** [comment]
That code is generated by Component with is the lib that is used for modularize List.js in the current version. No idea if you can remove those. Test and then run the tests.

For List.js in general it doesn't matter.

And in future versions I'm going to use Browserify instead of Component.

**Comment by wolffe** [comment]
Got it, thanks. I'm trying to minify the file and squeeze every last drop of disk space.

Looking forward to the updated version. Any ETA?
