### ISSUE TITLE
Can't use list.update() in mocha test

### ISSUE THREAD

**Issue by avcreation** [javve/list.js#337]
When trying to use the update method in a mocha test, I get 

    TypeError: 'undefined' is not an object (evaluating 'self.templater.clear')

Seems that the self.templater is not assigned correctly but can't figured out why...
Is there any known solution about this ?
Thanks in advance.

**Comment by javve** [comment]
I think we need to see some code here. I've never heard about this problem before :/
It seems likely that it's a implementation error in your tests and there by I'll close this issue, sorry.
