### ISSUE TITLE
Sort automatically

### ISSUE THREAD

**Issue by angelorocha** [javve/list.js#341]
Is possible sort a table automatically without the need of a button, i try:

< table data-sort="name">
...
< tbody class="list" class="name">
...
< tr> < td class="name">
...

**Comment by jardelvdm** [comment]
I would like to know the solution for it.

**Comment by ncbaihly** [comment]
There may be a better way to do this but the way I'm currently doing this is just doing a sort after setting up the list like this: 

```javascript
var list = new List('users', {
	valueNames: ['year', 'employeeName', 'supervisorName', 'status'],
	page: 10,
	plugins: [ ListPagination({})]
});

userList.sort('year', {order:"desc"});
```

If anyone has a way to just do it directly in configuration or there is a better way to do it, I'd love to know.

**Comment by javve** [comment]
I think that you'll have to sort manually for now.
Maybe I'll do something about this later :blush:
