### ISSUE TITLE
Add option to display a message for empty result ! 

### ISSUE THREAD

**Issue by naimhiq** [javve/list.js#342]
Hi guys,

Do you know how can I set to display a message if the user for instance searched for the keyword that doesn't not exist in the list?.By default listjs is giving empy line and not showing any message like "no match data found".

Thanks for your help !

**Comment by n00b3** [comment]
I had a similar need and was able to do it with some additional jquery. Get a count on the list items  each time search input is updated and then show/hide an element that contains the 'no match found' message. 

not out of the box, it works.

**Comment by naimhiq** [comment]
yeap thanks , I did fix that with some additional jquery ;)

**Comment by javve** [comment]
Here is an example: http://codepen.io/javve/pen/VvavzG

**Comment by mvkanha** [comment]
@javve Your many codepens are not working, please have look
