### ISSUE TITLE
Empty list display an inexistent element.

### ISSUE THREAD

**Issue by Moykn** [javve/list.js#343]
When the initialization is made using this options and an empty list:
```javascript
var options = {
  valueNames: ["text", "page"],
  item: "<div style='background:red;width:100px;height:30px;'></div>"
};
var userList = new List('users', options,[]);
```
The list shows an empty element node ss could be seen at this Pen:
http://codepen.io/anon/pen/BNxJxZ

**Comment by njt1982** [comment]
@Moykn - I am getting this too... Breaks search for me...

**Comment by njt1982** [comment]
Ahh...

Add:

```
userList.clear()
```

after defining it... 

Nasty "hack" ;)

**Comment by njt1982** [comment]
Revised Codepen - http://codepen.io/anon/pen/BNxMQx

**Comment by Moykn** [comment]
Tanks @njt1982. This solved the problem. 
Sorry for the late response.

**Comment by njt1982** [comment]
I would consider clearing the list on init a workaround for a bug.

IMHO it should not create the element and the fact it does is a bug/fault in the library.

**Comment by Moykn** [comment]
@njt1982 I agree with you. This is, surely, a bug. I was just saying "thanks for the help". :) 
English is not my first language, and i'm not proficient on it. So i think i could have been misunderstood.

**Comment by njt1982** [comment]
@Moykn - not a problem at all. Not misunderstood :) This is more for the developer(s) or listjs.

Once I got it working, it is really very good.

**Comment by and07** [comment]
```javascript
var options = {
  valueNames: ["text", "page"],
  item: "<div style='background:red;width:100px;height:30px;'><span class='text'></span><span class='page'></span></div>"
};

var userList = new List('users', options);


userList.add({text: 'text', page: 1});
```

**Comment by njt1982** [comment]
Thanks @javve

**Comment by Moykn** [comment]
Thank you @javve.
