### ISSUE TITLE
doesn't catch keyup event, triggered with jquery

### ISSUE THREAD

**Issue by slavugan** [javve/list.js#345]
I'm trying to chanhe data in search-field with jquety and then trigger keyup event  $('.search').trigger('keyup') or $('.search').keyup(), but list.js doesn't catch it. If I change data in search-field with keyboard filtering works good. Any suggestions?

**Comment by slavugan** [comment]
solved with dispatchEvent()

**Comment by ykadosh** [comment]
Thank you, I couldn't figure out why it was not working. For the sake of others who are having this issue, here's a code example:
```javascript
$('.search')[0].dispatchEvent(new KeyboardEvent("keyup")); // Works
$('.search').keyup(); // Doesn't work
```
This looks like a bug to me, so maybe you should keep this issue open.
