### ISSUE TITLE
Remove template table <tr> without an ID?

### ISSUE THREAD

**Issue by Jakobud** [javve/list.js#347]
I am using List.js with a table of elements. Initially in the HTML, the table has zero rows in the `<tbody>`. I compile a list of items in JS and then add them like this:

```
var myList = List("myid", options, myValues);
```

However, with tables, I have to have an empty `<tr><td class='name'></td><td class='whatever'></td></tr>` in the table that List.js can use as a template to create everything. So now I have this blank table row in there.

At first I tried to just do some jQuery: `$('tbody tr:first').remove()`. This worked, but I learned very quickly that when you sort items using List.js, the empty row is still apart of the dataset and it gets added back to the table.

I saw in the examples that I could do something like this to remove a row:
```
var itemId = $(this).closest('tr').find('.id').text();
contactList.remove('id', itemId);
```

But how would I do this with an empty/blank table row? What is the best approach to this? I'm sure I'm not the first to try this with tables.

**Comment by rwu1997** [comment]
Hey @Jakobud, what was your solution to this?
