### ISSUE TITLE
Feature request: Allow looking at data attribute instead of content

### ISSUE THREAD

**Issue by sprynmr** [javve/list.js#35]
When I'm sorting various things the default alphanumeric sort is nice, but doesn't cover all my needs. Many times I have to create a custom sort function, and its kind of annoying to only be able to sort on what information you are presenting in that tag. 

As an example, the alphanumeric sort can't handle $120,200.00 (dollar signs and commas). So I have to create a custom function, but in that function I have to manually strip out the $ and , before I have something I can work with sort wise.

**Comment by limist** [comment]
+1, this finer-grained sorting would be very useful.

**Comment by DamirSvrtan** [comment]
+1

**Comment by guedressel** [comment]
+1

**Comment by jenniferlsharps** [comment]
+1

**Comment by vincentorback** [comment]
+1

**Comment by mckeever02** [comment]
+1

**Comment by MikeMcChillin** [comment]
+1

**Comment by javve** [comment]
Sooo many +1 :grin: 
It'll be included in the next release -> a8e083dc0f642e90b7a3f3cc11b12f9bb353d3a0

**Comment by KRISHNA-DAS** [comment]
I've used the list.js with angularJs, And It was found that the list is not taking data throgh ng-repeat

**Comment by javve** [comment]
Haha, after FOUR frikking years is this feature finally added. Crazy, I know.
Release note: https://twitter.com/javve/status/705104547451170816 RT = :heart: :grin:

**Comment by javve** [comment]
Here is two examples:
http://www.listjs.com/docs#example-6
http://www.listjs.com/examples/data-attributes-custom-attributes

**Comment by maxoys45** [comment]
Hello @javve - Just started using List.js and really liking it so far, just wondering how you would go about filtering by data attr? I've managed to fork [this pen](http://codepen.io/anon/pen/QbOYaG) to filter by an elements content but can't see a way of doing this for a data-attr... here's how he does it:

`userList.filter(function (item) {
			if(activeFilters.length > 0)
			{
				return(activeFilters.indexOf(item.values().difficulty)) > -1;
			}
			return true;
		});`

He uses .values().[class name] to target it but it would be great if you could do this by data attr!

Thanks, keep up the good work :)

**Comment by eduo** [comment]
I'm not sure if I understand this. I should be able to tack multiple data attributes to the TR and sort by them, right?

I can't make it work at all. I'm probably missing something but I can't figure out what.

```
<div class="sortContainer">
	<span>Sort by:</span>
	<button class="sort" data-sort="lettersort">Greek Letter</button>
	<button class="sort" data-sort="countrysort">Country Name</button>
	<button class="sort" data-sort="numbersort">Ranking</button>
	<table class="TableToSort">
		<thead><tr><th>Country Ranking</th><th>Greek Letter</th></tr></thead>
		<tbody>
			<tr class="lettersort numbersort countrysort" data-lettersort="Alpha" data-numbersort="30" data-countrysort="Andorra">
				<td>#10<br>Spain</td><td>Alpha<br>Some Text</td>
			</tr>
			<tr class="lettersort numbersort countrysort" data-lettersort="Beta" data-numbersort="20" data-countrysort="Spain">
				<td>#10<br>Spain</td><td>Alpha<br>Some Text</td>
			</tr>
			<tr class="lettersort numbersort countrysort" data-lettersort="Gamma" data-numbersort="10" data-countrysort="Belgium">
				<td>#10<br>Spain</td><td>Alpha<br>Some Text</td>
			</tr>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	var sortOptions = {
		valueNames: [
			{ data: ['numbersort']},
			{ data: ['countrysort']},
			{ data: ['lettersort']}
		]
	};
	var requestList = new List('tableToSort', sortOptions);
</script>
```

 I apologize if I'm asking something obvious. There's not a lot of documentation, so I may be missing something obvious.
