### ISSUE TITLE
Sorting on a column that contains the same values

### ISSUE THREAD

**Issue by MongooseDoom** [javve/list.js#350]
I have this issue when I have a column that contains all the same values. If there are more than 10 rows, it, changes the order of items. If it has less than 10 rows, the order stays the same. It should be staying the same since all the values are the same.

10 Rows: http://codepen.io/MongooseDoom/pen/ZGPgrV
11 Rows: http://codepen.io/MongooseDoom/pen/BNbXYw

**Comment by javve** [comment]
Hmm, thanks for the example! I just created a special issue for all sorting related problems. #385
