### ISSUE TITLE
Radio/DropDown Sorting

### ISSUE THREAD

**Issue by sasscanoodle** [javve/list.js#355]
Hi,
Is there a way to filter using radio inputs and/or dropdown lists as an input, I have tried a few things and none have had any success. I don;t see an example of any kind of this implementation either.
Thanks in advance,
Brian

**Comment by scannermobs** [comment]
Yes, here is a bit of code to give you an example of usage:
[code]
$('#type-select').change(function(){
	var $val = $(this).attr('value');
	archiveList.filter(function(item) {
		var $item = item.values().datatype;
		if ( $item == $val) {
			return true;
		} else {
			return false;
		}
	});
});
[/code]
