### ISSUE TITLE
200 items limit?

### ISSUE THREAD

**Issue by hungerburg** [javve/list.js#356]
A table with 210 rows (declared in html source) only shows 200 rows, no indication whatsoever, not easily spotted at first ;) Found a hard-coded limit in the script and set to 500, but maybe this needs a little more love?
PS: Just found list.js and gave it a try; very nice, indeed!

**Comment by javve** [comment]
There is a setting called `page` that you can use :) Glad you like the lib!

**Comment by hungerburg** [comment]
I put "page: 500" into the options object of the constructor and could revert the source code change; still, an indicator that rows are omitted would be nice, for newcomers at least, probably pointing to the pagination plug-in; too lazy though, to create a pull request here. Thank you for sharing: What I was looking for was, a way to filter a table, that's what "search" does, and It proved quite useful, instantly.

**Comment by javve** [comment]
In the next version I've set the default 10 000 :)
The limit is due to performance reasons, but if someone experience those they can change it back to less.
