### ISSUE TITLE
Search/Fuzzy search not working for Divs 

### ISSUE THREAD

**Issue by matrixbegins** [javve/list.js#358]
I am trying to build a FAQ page, where all the FAQs are listed and on search using list.js we can filter them out. here is what I am trying: 

http://codepen.io/anon/pen/ojzEQb

However its not filtering the data. Can you guide me where I am wrong, or I have to restructure structure ?

**Comment by javve** [comment]
The fuzzy search does not handle long sentences or paragraphs due to performance reasons :cry:
