### ISSUE TITLE
Sort on table column with numeric data

### ISSUE THREAD

**Issue by cjohnsonuk** [javve/list.js#360]
I'm just starting with listjs (this morning)
I took this example : http://www.listjs.com/examples/table
and added two additional table columns, one called "town" with alphanumeric data and one called "number" with numbers in it.  
I then moved the sort button into a header row of the table and made one for each column:
```html
    <tbody class="list">
    <tr>
    <th><button class="sort" data-sort="name">Sort by Name</button></th>
    <th><button class="sort" data-sort="Town">Sort by Town</button></th>
    <th><button class="sort" data-sort="born">Sort by Year</button></th>
    <th><button class="sort" data-sort="number">Sort by Number</button></th>
    </tr>
```
I added the additional columns in order to the var options : 
```javascript
    var options = {
	valueNames: [
		'name',
		'Town',
		'born',
		'number'
		]
	};
```
The alphanumeric columns sort correctly with the buttons remaining in the header row at the top of the table. The numeric columns, when sorted, result in all the sort buttons moving between the top and bottom row of the table.  Here's some things I tried: 
- Moving the column to a different position in the table ( to see if it was just the first/ last/middle columns that failed): Header row with buttons moves between top and bottom.
- Using Firefox or Chrome  : Header row with buttons moves between top and bottom
- Adding alpha characters to the numeric table data (prefixed with an "a") : buttons in the header remain at the top
- Adding " " before the table entry : Header row with buttons moves between top and bottom
- Adding "&nbsp" before the table entry : buttons in the header remain at the top
I can split the buttons row into another table and this appears to work fine although it would be nice to have it all as part of the same table

Is this something that is expected?
Am I doing something obviously wrong?

**Comment by cjohnsonuk** [comment]
FIxed it : Missing <thead> </thead> tags around the header row...

**Comment by javve** [comment]
:+1:
