### ISSUE TITLE
Filtering based on a value works inconsistently

### ISSUE THREAD

**Issue by KaurKirikall** [javve/list.js#361]
I've integrated a javascript filtering system provided in examples and in a popular codepen I found for list.js button filtering, but it filters all 10 of the necessary items and then throws in 1-2 items that are not meeting the criteria, but are still listed.

You can see and try to understand the issue here. 

http://swg.aiti.ee/startups/

**Comment by javve** [comment]
I can't see this error. I guess you solved it? :grin:
