### ISSUE TITLE
Back button to page containing List reverts to original sort/filter state

### ISSUE THREAD

**Issue by jhgarrison** [javve/list.js#364]
If you navigate back to a page containing a List using the back button, the list is presented in its original order and filter state, not the state when the user left it (i.e. by selecting an item in the sorted/filtered list).

This is a well-known problem and not List.js's fault, but in order to work around this we need access to the current filter and sort state, so we can encode them into the location hash.  

I found the `buttons` var in the sort module but it does not seem to be exposed/accessible from the `List` object in the browser.

**Comment by lekkerduidelijk** [comment]
@jhgarrison Did you perhaps do any work on this? I'm looking for a similar solution.

**Comment by lekkerduidelijk** [comment]
I see #70 is related and we should use a plugin for this.

**Comment by jhgarrison** [comment]
On 12/2/2015 4:22 AM, Rutger Laurman wrote:
> I see #70 <https://github.com/javve/list.js/issues/70> is related and we
> should use a plugin for this.

I rolled my own by encoding the current sort/filter state into
a string which gets saved in window.location.hash.  It's specific
to my situation and not really in a form suitable for publishing.

-- 
Jim Garrison (jhg@acm.org)
PGP Keys at http://www.jhmg.net RSA 0x04B73B7F DH 0x70738D88

**Comment by lekkerduidelijk** [comment]
Thanks, I did the same thing, also rather specific :wink:

**Comment by javve** [comment]
:+1: :wave:
