### ISSUE TITLE
Sorting items with numbers first and others with letters first causes number to stick to top.

### ISSUE THREAD

**Issue by briancompton** [javve/list.js#365]
When I create list with items such as "4 Ways to Leave", "The Headline", and "Another Headline", the "4 Ways to Leave" sorts to the top whether using ascending or descending. I've modified the example CodePen to demonstrate at http://codepen.io/anon/pen/KdbxOv.

**Comment by javve** [comment]
Hmm, thanks for the example! I just created a special issue for all sorting related problems. #385
