### ISSUE TITLE
Sorting animation

### ISSUE THREAD

**Issue by kmligue** [javve/list.js#366]
Anyone have successfully implemented a sorting animation in this plugin? Like doing animation when the list is reordered. I've been digging on this for a day now and i can't figure it out.

**Comment by javve** [comment]
I think that is hard unfortunately :cry:
BUT I'm actually working on a new lib related to this. Follow twitter.com/javve to keep updated ;) (no ETA yet)

**Comment by hallaathrad** [comment]
What I've done is add [animate.css](https://daneden.github.io/animate.css/) to the list's elements. It does the trick well enough.

**Comment by vitoo** [comment]
I used animate.css like @hallaathrad 

```js
 yourList.on('updated', function (list) {
       //every updated element take animation
        list.matchingItems.forEach(function (element) {
            var id = element.elm.id;
            $('#' + id).addClass('animated fadeIn');
        });
```

Thank you

**Comment by radioactiveboyx** [comment]
i did it directly as well

> What I've done is add [animate.css](https://daneden.github.io/animate.css/) to the list's elements. It does the trick well enough.

i did it directly as well using both ideas @vitoo 

   listObj.on('updated', function (list) {
    $('.name').addClass('animated fadeIn');
    });

**Comment by ekerstein** [comment]
Has anyone come up with a better solution for this?

I'm forcing a sort via listsort.sort() and I want the items to move slowly, not instantly.

I tried the CSS library mentioned above but that doesn't work for this case.

**Comment by akoshy21** [comment]
If anyone's still interested, I was able to get some simple speed-configurable sort animations working. It's pure JS and works by adding some hooks to the sortStart and sortComplete events based on this [medium article](https://medium.com/developers-writing/animating-the-unanimatable-1346a5aab3cd).

   ```
let oldPos = {};
 function onSortStart(list) {
        list.matchingItems.forEach(function (element) {
            oldPos[element.elm.id] = element.elm.getBoundingClientRect();
        });
    }

    function onSortComplete(list) {
        list.matchingItems.forEach(function (element) {
console.log(element.elm.id);
            const newBox = element.elm.getBoundingClientRect();

            const deltaX = oldPos[element.elm.id].left - newBox.left;
            const deltaY = oldPos[element.elm.id].top  - newBox.top;

            window.requestAnimationFrame( () => {
                element.elm.style.transform  = `translate(${deltaX}px, ${deltaY}px)`;
                element.elm.style.transition = 'transform 0s';

                window.requestAnimationFrame( () => {
                    element.elm.style.transform  = '';
                    element.elm.style.transition = 'transform 500ms';
                });
            });
        });

    }

```

I've got a working demo with list.js here:
https://jsfiddle.net/akoshy/1f4v09dc/7/
