### ISSUE TITLE
problem with sorting UTF8 Czech characters

### ISSUE THREAD

**Issue by dkocich** [javve/list.js#370]
Hello,

just to let you know about some tips for next versions...

my czech language content always messes up after sorting. Special characters should be inside the list (not at the end). It could be good to set sorting language (to use its rules for sort). I use list js in multilanguage page so english should sort differently than czech.

Czech alphabet is like this:

a, á, b, c, č, d, ď, e, é, ě, f, g, h, ch, i, í, j, k, l, m, n, ň, o, ó, p, q, r, ř, s, š, t, ť, u, ú, ů, v, w, x, y, ý, z, ž.

and when together with big letters then it is like this:

A a Á á B b C c Č č D d Ď ď E e É é Ě ě F f G g H h Ch ch I i Í í J j K k L l M m N n Ň ň O o Ó ó P p Q q R r Ř ř S s Š š T t Ť ť U u Ú ú Ů ů V v W w X x Y y Ý ý Z z Ž ž

Thanks for great work.
Have a nice day.

![image](https://cloud.githubusercontent.com/assets/6165660/11609644/7903fde4-9b8c-11e5-9e38-ba22397b72d4.png)

**Comment by javve** [comment]
Thanks for input! :+1: This is a known issue that I don't really know how to solve efficiently right now. I'm open to pull requests here: https://github.com/javve/natural-sort
