### ISSUE TITLE
Multiple search terms without fuzzy-search plugin

### ISSUE THREAD

**Issue by claudiodestasio** [javve/list.js#371]
Sorry for my bad english ;)
I need to specify multiple search terms and the fuzzy-search plugin does not work (for me) with very long strings in li elements.
They are not practical with javascript but hacking the code would find a solution with the following change using regex (lines 1000 to 1005 about):

```javascript
values: function(values, column) {
            if (values.hasOwnProperty(column)) {
                text = toString(values[column]).toLowerCase();
                 
                 var searchRegex = "(?=.*"+searchString.replace(/(?:\W+)/g,")(?=.*")+").*";
                 var searchRegexObj = new RegExp(searchRegex,"i");
                 
                 
                if ((searchString !== "") && (text.search(searchRegexObj) > -1)) {
                    return true;
                }
            }
            return false;
        }
```

It 'a too expensive solution in terms of resources? Is there a more elegant way to achieve the same result?

**Comment by javve** [comment]
I've been thinking about allowing regex as an options in the search, but haven't added that feature yet. But you can add your own custom search function. See https://github.com/javve/list.js/blob/master/test/test.search.js#L97
