### ISSUE TITLE
Click event not work

### ISSUE THREAD

**Issue by skiokko** [javve/list.js#373]
Hi,
I already fixed the problem by set directly on list item the JS code onclick="myfunciton()":

< ul class="list">
< li onclick="myfunciton()></li>
< li onclick="myfunciton()></li>
< li onclick="myfunciton()></li>
< /ul>

Anyway i report you my issue: after I search some element and list is updated, the items not run nomore the click event of codes:

$("list li").click(function () { ... }); same for $("list li").on('click',(function () { ... });

Work only first items, strange situation. I know is not a problem of your plugin but this is problem:

JQuery events click not work on dyamically generated HTML elements...happen me many times, never found a solution...

Thanks

**Comment by javve** [comment]
A better solution is to use something like this:
```
$(document).on('click', '.list-item-class', function(e) {
  console.log('omgomg');
});
```
