### ISSUE TITLE
Example tabs don't work

### ISSUE THREAD

**Issue by xDaizu** [javve/list.js#374]
In the website, no example other than the first one ("existing list") show the HTML, CSS and JS tabs (tried in Chrome 47.0 and Firefox Developer Edition 45.0)

**Comment by javve** [comment]
Seems like it was a temporary problem with Codepen? Works for me now.

**Comment by xDaizu** [comment]
Now, tried both in `Firefox Developer Edition 46.02a` and `Google Chrome 48.0.2564.116 m`
[Existing list](http://www.listjs.com/examples/existing-list) -> Works :+1: 
[Existing list + add](http://www.listjs.com/examples/existing-list) -> No works :-1: 
[New list](http://www.listjs.com/examples/new-list) -> No works :-1: 
[Table](http://www.listjs.com/examples/table) -> Works :+1: 
[Add, get, remove](http://www.listjs.com/examples/add-get-remove) -> Works :+1: 
[Fuzzy search](http://www.listjs.com/examples/fuzzy-search) -> Works :+1: 
[Pagination](http://www.listjs.com/examples/pagination) -> No works :-1:

**Comment by javve** [comment]
Hmm...
Which OS? What does the developer console say?

**Comment by xDaizu** [comment]
Windows 7. 

Screenshot attached 
![list js-error](https://cloud.githubusercontent.com/assets/7584835/13320421/2a91b052-dbc9-11e5-8111-6c7a1fc8795f.png)

**Comment by javve** [comment]
:( Seems like a problem with Codepen. Can you see the example if you go to the Codepen website?

**Comment by xDaizu** [comment]
I think I found a pattern... 
(Look at the HTML)

![eg1](https://cloud.githubusercontent.com/assets/7584835/13323897/cefa7f54-dbdb-11e5-92a9-6c4ea8985a25.png)
![eg2](https://cloud.githubusercontent.com/assets/7584835/13323899/d2ebb8da-dbdb-11e5-9142-126860e269c9.png)
![eg3](https://cloud.githubusercontent.com/assets/7584835/13323906/d8f0b136-dbdb-11e5-857f-3999e0c05501.png)
