### ISSUE TITLE
Default sort order

### ISSUE THREAD

**Issue by hamsterwork** [javve/list.js#379]
First, thanks for such a script!

I need one small change for my using. When you click on sort button, items sort by asc and only after next click - by desc. I want to sort them first by desc.

I've thought about creating another buttons and activate list.sort() after clicking them, but it seems too complex. Can I change default sorting without this?

**Comment by alexbahl** [comment]
you could just call the sort function in your js to have it auto sort by  desc. 

yourList.sort('what to sort', { order: 'desc' });

**Comment by javve** [comment]
What alex said. :)

**Comment by bdparker** [comment]
This is good, but the list has to load and then snap to the sorted view. Is there a way to sort before the list is loaded?
