### ISSUE TITLE
How to get version 1.2.0?

### ISSUE THREAD

**Issue by wolffe** [javve/list.js#381]
How do I compile and get the latest version in one minified file?

**Comment by javve** [comment]
Read here: http://www.listjs.com/overview/contribute

```
npm install
grunt dist
```

**Comment by wolffe** [comment]
What if I don't have access to npm or grunt tools? Can't I just download a JS script?

**Comment by javve** [comment]
Here you go: http://cl.ly/1Z080R2f293p :)

**Comment by wolffe** [comment]
Great, thanks!

One of my WordPress plugins depends on list.js and the latest update fixes some outstanding issues.
