### ISSUE TITLE
using page and indexAsync

### ISSUE THREAD

**Issue by kirancheema** [javve/list.js#382]
Hi I've been having a play with the list.js plugin and it is a really useful plugin. 

I have come across a (maybe) issue? 

I've found that if I use page:1200 

It works fine loads the list up fine, a little slow but its a long list... 

If I then try and add in indexAsync:true 

it seems to default back to the default page:200

There is the following error in the console log : Uncaught ReferenceError: init is not defined

Is it Quicker to generate from existing list or to create on initialisation?

**Comment by javve** [comment]
Duplicate #268.
It should be faster to create on initialization.
