### ISSUE TITLE
When will a new version be released?

### ISSUE THREAD

**Issue by tpinne** [javve/list.js#384]
Hi,

I've seen there is some work going on for a 1.2.0 release. When will this be finally available? In a current project we are in actual need for data-attributes as filter values. I've tried the file you linked in the comments of #381 but a console log on item.values() inside a filter function gives me an object with the correct keys but empty values.

Any ideas or hints?

**Comment by javve** [comment]
Hmm, can I get some code here? It should work™

**Comment by tpinne** [comment]
I put together this gist https://gist.github.com/tpinne/690e267d0dd5e643dff5 

There is a console.log of the items array where _values has empty values. And there is a disabled filter function to output every items values during filter. also empty.

I'm pretty sure I misunderstood how to place the data-attributes...

**Comment by javve** [comment]
Oh, yeah, you've misunderstood how to init a list with data-attributes (understandable since there are no documentation).

This is how you should do:
```javascript
var options = {
  valueNames: [
    { data: [ 'saltNumber', 'type', 'intolerances' ] }
  ]
};
```

**Comment by tpinne** [comment]
Ok, thanks! works fine!!! I tried many sorts of guessing the right syntax. But that wouldn't come into my mind anytime soon ;)
