### ISSUE TITLE
Natural sort chunk error

### ISSUE THREAD

**Issue by tbaconscius** [javve/list.js#387]
Hi.

There is a bug in the sort algorithm related to chunking the text to be sorted. If you for example have a list with the elements "Test" and "Test1Test2" a javascript error occurs in the browser.

I have tracked the issue down to be when you call the normChunk function. Here the two strings are chunked into two arrays of length 1 and 4. However, you forget to pass empty string to the function if xN[cLoc] or yN[cLoc] is undefined - which is the case when you in the loop tries to lookup xN[1] in the array with only one element.

You refer to the algorithm at https://github.com/javve/natural-sort but I can also see that you have changed a lot in this algorithm, for example you have removed the undefined check.

The bug was found in version 1.2.0.

**Comment by steveoh** [comment]
I'm running into this issue also.

```js
    oFxNcL = normChunk(xN[cLoc] || '', xNl);
    oFyNcL = normChunk(yN[cLoc] || '', yNl);
```

does seem to fix the issue.

**Comment by mattjacob** [comment]
[This issue](https://github.com/overset/javascript-natural-sort/issues/21) was fixed in the [javascript-natural-sort](https://github.com/overset/javascript-natural-sort) project last year. It seems like the changes just need to be backported.

**Comment by francispelland** [comment]
Also running into this issue.  In my case breaking on string that have a number in it, without a space like "Bill-To Phone1 Extension".
