### ISSUE TITLE
Lost items after reIndex() with a filter applied

### ISSUE THREAD

**Issue by fenixkim** [javve/list.js#388]
I have a list with a filter applied, then I call the **reIndex()** method. The hidden items by the filters cannot be displayed again when I disable the filters.

Can you confirm this issue? or is it something normal?

**Comment by javve** [comment]
Yeah, that's kind of intentional, or well, rather a side effect of the `reIndex()` method. The method removes all existing items in the list and then parses the DOM it finds in the list and then creates new items. If you've filtered/hided anything it'll disappear :confused:

**Comment by guillaumebdx** [comment]
@fenixkim 
If you use ajax and want to reindex, you can do it to retrieve everything after the ajax call :
yourList.filter();      //reinitialise list (add all items in dom) 
yourList.reIndex(); //reinitialise index with items in dom
projectFilter();       //apply filter
//projectFilter is th name of my function who initialize variables with filters checked and selected. This function embedded :
userList.filter(function(item) {
// (...) code here with res = true/false
});
