### ISSUE TITLE
Browserify Issue

### ISSUE THREAD

**Issue by steveoh** [javve/list.js#391]
I forked and cloned list.js.
`npm installed` and ran `grunt dist`

It didn't work unless browserify was global installed.

I would imagine the `shell:build` command should be rewritten from

`command: 'browserify index.js > dist/list.js'`
to
`command: 'node_modules/browserify/bin/cmd.js index.js > dist/list.js`

This would make it use the `"browserify": "^13.0.0"` devDependency in the package.json.

I can send this as a PR if you're interested since i've already made the change.

**Comment by javve** [comment]
Ohh, good point! Thanks a lot!
