### ISSUE TITLE
Vital Sorting improvement

### ISSUE THREAD

**Issue by AAllport** [javve/list.js#402]
Hello
i am using list js for a project of mine and i needed to know if there was a way of restricting the sort direction so that someone sorting by name (for example) cannot sort by name in reverse. this is essential for the project an if there is not a way of doing such thing (i can use javascript event triggers if that would help) i will half to move away from this otherwise amazing libray
i hope this is resolved
A

**Comment by javve** [comment]
Instead of using the automatic sort buttons you could create your own sort button that only sorts one way via the `.sort` method. http://www.listjs.com/docs/list-api#sort
