### ISSUE TITLE
Options - option to specify which column(s) to automagically search

### ISSUE THREAD

**Issue by charliedotau** [javve/list.js#418]
The Automagic Search is great.  However as far as I can tell, having the search automagically setup, there is no way to specify which column(s) to search.  

As such I propose an option for this in the Options object.

Thanks
Charlie

**Comment by vanduynslagerp** [comment]
You can use `searchColumns` in the options when you initialize the list like this:

`var options = {
  valueNames: [ 'name', 'lastname','birthdate' ],
  searchColumns:[ 'name', 'lastname' ]
};
var userList = new List('users', options);`

In this example you would have 3 fields (name, lastname, birthdate) and the search function would use only name and lastname.

**Comment by charliedotau** [comment]
ah, yes, thanks.  easier than I thought.thanks.

**Comment by Phoenix09** [comment]
just going to point out this isn't mentioned anywhere in the docs.
