### ISSUE TITLE
Add eventListeners to the item element

### ISSUE THREAD

**Issue by deiu** [javve/list.js#420]
Hi,

First of all, thanks for all the effort you put into this library!

I was wonder if there is an easy way to attach an event listener to when generating the template. For example, I would like to attach an `onclick` even listener to every `<li>` element in the list.

**Comment by benjamin-richardson-rr** [comment]
It would probably be more efficient to attach a event listener to the <ul> that tracks all of the <li> from there. It will be many less listeners, and it will work much better as it will remain attached as the DOM elements are removed and re-added.

$( ".my-list" ).on( "click", ".my-list__item", function() {
  ...
});

**Comment by javve** [comment]
Thanks @deiu !
Yeah @benjamin-richardson-rr has a good solution!
