### ISSUE TITLE
Noob question - Get the size of the list after filter is applied. 

### ISSUE THREAD

**Issue by Snowbell92** [javve/list.js#422]
This is more of a how-to question, but I haven't been able to solve it (I'm not really good with javascript). I have show the size of the entire list with the `size()` method, but how do I update if after a filter has been selected? I have tried putting in an `if-else` condition, but it is not working. Tried it with `matchingItems().length` too. Thanks in advance.

**Comment by fuchsteufelswild** [comment]
It's because matchingItems is not a method, it is a property. 
So you have to do something like this: `mylist.matchingItems.length`
See here: http://www.listjs.com/docs/list-api
