### ISSUE TITLE
If list contains list，how to use?

### ISSUE THREAD

**Issue by szhupeng** [javve/list.js#423]
If there is a list,and the list contains a list,how to use?

**Comment by ppscvalentin** [comment]
I was also wondering the same thing. I have a list of faculties grouped by universities. How can I filter faculties but also show the list group header for groups with at least 1 result?

**Comment by srivignes** [comment]
@javve  I've a list inside a list.  Always when I do a search, only the outer list get searched. So could you please help me with a solution to it ?

**Comment by zeusbangayan** [comment]
I have this issue where I need to filter by country, by city.

It filters the city but only the first item on the city.

![sample](https://cloud.githubusercontent.com/assets/5523635/16271487/cee35af6-38cc-11e6-86b0-45ed13143c3e.jpg)

**Comment by josean100** [comment]
Is it possible to add search subdirectories taking advantage of this script?
    
function buildNarrowNodeTree(treeData, root, depth) {
        // get the item names from treeData and save their index number
         var keyNames = new Array();
         for (var i = 0, numItems = treeData.length; i < numItems; ++i) {
             keyNames[treeData[i].name] = i;
         }
         // sort the names we found in treedata
         var keyList = new Array();
         for (key in keyNames) {    keyList.push(key); }
         keyList.sort();

        for (var i = 0, numItems = treeData.length; i < numItems; ++i) {
            var dirItem = treeData[keyNames[keyList[i]]];
            var oData = new Object;
            oData.expanded = false;
            oData.label = fit_string(dirItem.name, maxLabelLengthNarrow - (depth * 2));
            oData.title = dirItem.name;    // so user can see entire filename in tooltip
            if (dirItem.type == 'folder') {
                oData.expanded = true;
            } else {
                oData.href = dirTreeBaseURL + dirItem.path;
            }
            var tmpNode = new YAHOO.widget.TextNode(oData, root);
            tmpNode.labelStyle = "icon-" + dirItem.extension;
            if (dirItem.type == 'folder') {    // recursive call to display children too
                buildNarrowNodeTree(dirItem.children, tmpNode, depth+1);
            }
        }
    }

**Comment by javve** [comment]
I'm sorry but List.js does not support lists within lists. However, nothing stops you from creating multiple List.js instances which uses the same search field.
