### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Hellek** [javve/list.js#433]
Hi, is someone know how to fix this bug https://jsfiddle.net/ouwde3wd/ ?
It's show self if list contain a lot of identical strings (more than 50 or 100 or something like);

update 1.0: Last version of list.js fixed this error, but there is another problem, for now list not filter all list, just one string without 5 goes on top wher sort button is pressed.
p.s.s.  Thank you Jonny for this great extension!

**Comment by EugeneTM** [comment]
@Hellek the problem is solved

**Comment by javve** [comment]
Yeah, if you toggle asc/desc on a list with multiple occurrences of the same string it won't flip the sorting order completely, I'm sorry but that is not a prioritised issue right now and I don't have a clear ide exactly how to solve it in a nice way.

But I'm glad that you like List.js anyways! :D

**Comment by EugeneTM** [comment]
I have solved it! Just cannot merge for now. Would you have interest in the
solution?

4 февр. 2017 г. 5:33 PM пользователь "Jonny Strömberg" <
notifications@github.com> написал:

**Comment by Hellek** [comment]
@EugeneTM The problem not actual. I forget how i solve it, i can suggest that i update list.js to latest version. Anyway if my suggestion is wrong it would be a great if you share your solution with community))

**Comment by thewasta** [comment]
Is it fixed in current version? I have this problem and don't know how to fix it, if anyone has a idea... Thanks
