### ISSUE TITLE
First element values disappear on existing list

### ISSUE THREAD

**Issue by questionablequestion** [javve/list.js#436]
Hey,

I have existing list but all text for first element (that I use in valueNames) disappear. 

JS
```
var options = {
            valueNames: [ 'name', 'price'],
            item: 'itemBlock'
        };

var list = new List('test', options);
```

HTML
```
<div id="test">
  <div class="list">
    <div id="itemBlock">
      <div class="name">Name 1</div>
      <div class="price">3.33</div>
    </div>
    <div id="itemBlock">
      <div class="name">Name 2</div>
      <div class="price">6.66</div>
    </div>
    <div id="itemBlock">
      <div class="name">Name 3</div>
      <div class="price">9.99</div>
    </div>
  </div>
</div>
```
(I'm familiar that multiple id's are bad practice but this is how plugin require, right?)

And now, **Name 1** and **3.33** would disappear while others will work fine.

What am I doing wrong here? If I c/p some example from the page, it works perfectly. Can you use div's for this or just ul/li or table?

Thanks

**Comment by javve** [comment]
Ah, no, you're combining two initiation methods at the same time. Id's and the `item` option is not needed if you have items in the list on initiation. Just remove the id's  and `item`.
