### ISSUE TITLE
The list need to have at list one item on init otherwise you'll have to add a template.

### ISSUE THREAD

**Issue by artknight** [javve/list.js#438]
_The list need to have at list one item on init otherwise you'll have to add a template._ error message gets thrown if there are no items in the list. 

I think the process should **not** throw an error.

**Comment by mikevaleriano** [comment]
Looks like whenever this error is thrown the other tables/lists after the one causing problems do not work anymore.

**Comment by klonos** [comment]
...besides, the "have at l**i**st one item" part of that message should have been "have at l**ea**st one item"

**Comment by nkgilley** [comment]
This broke with #634. Please reopen
