### ISSUE TITLE
Cannot use trigger('click') or click on pagination

### ISSUE THREAD

**Issue by oninross** [javve/list.js#452]
Assigning click events on the pagination does not enable JavaScript to dynamically trigger the page.  I am following one of the issues (https://github.com/javve/list.pagination.js/issues/6) and applied it to my code and nothing happened.  

Having that said, it still doesn't solve the issue of developers triggering the pagination using javascript

**Comment by iszlailorand** [comment]
i had the same problem, but i soleved it with dynamically assigned click events. Something like > $(where to check for dynamically created selector).on('click', 'dynamical selector', function(event) {your funny stuff here} ... have luck.

**Comment by javve** [comment]
I'm not sure why you can't use trigger('click') (maybe the requires that the listener have been added by jQuery?), but in next version (see reference from commit) you can see with `page` and `i` each pagination link triggers. So instead if clicking them you can see the data attribute and do the change yourself via `listObj.show(i, page)`, ref: http://listjs.com/api/#show

**Comment by hitolonen** [comment]
@javve on pagination click we would need to scroll back to top/specific page element as clicking to another page doesn't do it by default. How can we achieve this?

**Comment by 4loop-co** [comment]
```
$(document).on('click', 'a.page', function() {
         $('html, body').animate({
             scrollTop: $('h1').offset().top
         }, 500);
     });
```

**Comment by Stolzenhain** [comment]
> This should do it.

here's a variant without jQuery:

```
document.addEventListener( 'click', function( event ){
    if ( !event.target.matches( '.pagination [a|button]' ) ) { return; }
    // do scrolling here
} );
```
