### ISSUE TITLE
back button on pagination

### ISSUE THREAD

**Issue by krishnnamohan** [javve/list.js#460]
when i hit a back button with href="javascript:history.go(-1)" it is taking me to the first page whereevr i am on the pagination

**Comment by jpdevries** [comment]
I'm trying to add History support with the HTML5 Push API. When I push a new history in the state it works fine but when I call .update() on the list it destroys the history state (can't use the forward button).

**Comment by javve** [comment]
I'm sorry but some kind of history support is not planned at the moment 😢
