### ISSUE TITLE
Pagination plugin: infinite loop which hangs the page when list initialized with page=0

### ISSUE THREAD

**Issue by fedulovivan** [javve/list.js#469]
Hello! Internal method 'refresh' of ListPagination module enters infinite loop if value of page option is equal to zero. This leads to hanging of entire browser page.
![image](https://cloud.githubusercontent.com/assets/752105/20593703/6d7ff03e-b244-11e6-8d3a-726cd8b87398.png)

**Comment by lalexx** [comment]
Really dangerous bug!
