### ISSUE TITLE
Docs for pagination contain some bad information

### ISSUE THREAD

**Issue by ethanclevenger91** [javve/list.js#470]
The [pagination docs](http://listjs.com/docs/plugins/pagination/) contains a couple of typos/bad information, specifically the CDN snippet. It references it as a stylesheet and the URL there is not valid. Should be swapped with `//cdnjs.cloudflare.com/ajax/libs/list.pagination.js/0.1.1/list.pagination.min.js`, unless there's a newer version. That's the one used in the CodePen example, anyway.

**Comment by javve** [comment]
Thanks! It's been fixed now!
