### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by hubdotcom** [javve/list.js#473]
http://listjs.com/examples/table/

**Comment by leecollings** [comment]
I can't see anything wrong with the demo...

**Comment by hubdotcom** [comment]
http://s.codepen.io/javve/fullembedgrid/oEezp?type=embed&animations=stop-after-5
![screenshot 2016-12-14 10 19 23](https://cloud.githubusercontent.com/assets/5274747/21178310/d1a9a7b0-c1e6-11e6-96e2-cdf9f8ec4f95.png)

**Comment by nekromoff** [comment]
Same 404 for me

**Comment by OmgImAlexis** [comment]
It's because of mixed content. The frame is loading over HTTPS and then inside of the frame it's requesting a HTTP file. In the codepen replace the list.min.js link with the HTTPS cdnjs one and it'll fix this.

**Comment by javve** [comment]
Oh, thx! Fixed!

**Comment by viliusle** [comment]
Still broken, does not load.

**Comment by javve** [comment]
It broke again @viliusle , and now it's fixed again 😅
