### ISSUE TITLE
Not really an issue, need help with searching for hidden child items

### ISSUE THREAD

**Issue by leecollings** [javve/list.js#474]
My scenario involves a list of divs, some of which are hidden by using Bootstrap's collapse feature.

By default, only some certain divs are shown, which List is able to filter out absolutely fine, it's the hidden ones that I Would also like to be able to filtered, and made to be shown if they are picked up within the search.

Can this be added to the options at all, to change CSS styling for child items when performing searching?

**Comment by javve** [comment]
Sorry, but this doesn't sound like something List.js will support 😢

**Comment by lsrocha** [comment]
@leecollings It can be done listening to the searchComplete event. Listjs provides the "visibleItems" parameter, which lists all maching items. If an item maches and must be shown, you remove a CSS class.
