### ISSUE TITLE
Not searching all data 

### ISSUE THREAD

**Issue by jesperweltz** [javve/list.js#475]
Hi
I have a issue where it's not searching all the data

We have made a list of retailers. But it's not searching zip code, address and web page, everything else is being searched. I can not figure out why

We are adding all the data as "valueNames", to my eye it should work :)

```
var options = {
	    valueNames: [ 'title', 'address', 'zip', 'city', 'country', 'tel', 'mail', 'web' ]
};
retailersFilterList = new List('resellers', options);
retailersFilterList.sort('zip', { order: "asc" });
```

you can see the actual page here: [resellers](http://scrouples.dk/forhandlere/)

**Comment by javve** [comment]
Hmm, when I tested with `1850` (to search zip) now it seems to work? Please get back with an exact example search if it's still a problem :)
