### ISSUE TITLE
Creation of list using list template ignores extra template items (e.g. checkboxes)

### ISSUE THREAD

**Issue by jyting** [javve/list.js#481]
Hi,

Given this particular template for trying to create a fuzzy search:
`    var options = {
        valueNames: ['pkg-name'],
        plugins: [ListFuzzySearch()],
        item:"<li><label class='pkg-name'><input class='pkg-name' type='checkbox'></label></li>"
    };
`

The fuzzy search functionality works as expected (actually the string difference algorithm is a bit weird - the term 'wake' gave results without the letter 'k' in them, but that's another story), but they weren't checkboxes - upon inspecting the html of the generated item, I was only left with a `<li><label></label></li>` HTML block - no checkbox in sight. Would it be possible to fix this functionality so that any HTML in the template is added to the resultant DOM item/s?

**Comment by javve** [comment]
Hi! I need to see more code to help you here. But one thing is that you should not use the same class two times in the same item `pkg-name`.
