### ISSUE TITLE
Error: Cannot find module 'string-natural-compare'

### ISSUE THREAD

**Issue by noahmanger** [javve/list.js#483]
I see that in v1.4.0 you changed the sorting library to use `string-natural-compare`.  By just running `npm install` with an empty `node_modules` directory, and then building my script I'm getting the error that it can't find `string-natural-compare` module. If I manually install that package, the build works. I'm stumped why it's not seeming to download the package automatically. Any ideas?

Also, thanks for the great library.

**Comment by javve** [comment]
Hmm, sounds really weird 😕

**Comment by AKST** [comment]
Is it likely that it's because listed in devDependencies while it's still included in the final build? Resulting in NPM not downloading it when it's used as a dependency?

**Comment by thedamon** [comment]
Yep. For some reason I'm not getting that error locally, but I am in production.

I suspect it might be the version of NPM being used... ?

**Comment by javve** [comment]
Oh, yeah that's correct @AKST! I'll fix that and do a new release!

**Comment by javve** [comment]
Fixed!

**Comment by noahmanger** [comment]
Thanks!
