### ISSUE TITLE
Updating pagination page size programmatically?

### ISSUE THREAD

**Issue by cfrefah** [javve/list.js#492]
Hi, thanks for a great plugin!

I'm trying to implement a page-size-option dropdown but I'm having trouble updating the list accordingly. Setting a new page-property value on the list and running update() plus reIndex() doesn't work. The paging buttons are updated but the items in the list are not. I've tried to set the page-size option via code, and managed to get it to respond to, for example, from 50 to 25. But if i try to change it back to 50, it still only has 25 items in the list, even though I've run "update()". I'd be grateful for any input regarding this, thanks!

**Comment by javve** [comment]
The show method should solve your problem :)  http://listjs.com/api/#show

**Comment by cfrefah** [comment]
Thanks, 
Just tried that, and now the pagination breaks.
I re-initialize the list with new pagination-page size-parameter, I reIndex(), update(), then show(1, size).
I've also tried diffrent permutations of that order. Now the pagination only shows one page, regardless of how big the initial list is...

**Comment by cfrefah** [comment]
Ok, solved it with some DOM-manipulation. I cache the "default"-list, and re-attach it to the DOM after each change of the page-size-parameter-dropdown, then re-initialize the list. Seems to work fine.

**Comment by Tsm012** [comment]
Not sure exactly how you've setup you table, but javve is right, you don't even have to call update, in the function that handles your page length changing, simply update the table or list with 

var pageLength = $('#yourpagelengthid').val()

List.show(0, pageLength)

hope that helps someone looking for help

**Comment by cfrefah** [comment]
Ah, thanks!! Almost too simple!
