### ISSUE TITLE
Compatibility with AngularJS ng-repeat

### ISSUE THREAD

**Issue by bwheeler181** [javve/list.js#496]
Hello,

It looks like the library as it stands is incompatible with using AngularJS ng-repeat inside of an element with class="list", since the Templater clear() function removes all content within that element. This has the effect of removing the comments that AngularJS uses to know where to begin inserting the elements from its ng-repeat iteration.

(This method involves using list.js by extracting the relevant list information from existing HTML)

The solution I developed just skips over childNodes with the nodeName "#comment" or "#text," which might not be the most graceful workaround, but does produce the intended effect. Any chance for a more official solution?

Great tool, by the way. Thanks!

**Comment by javve** [comment]
Hi! I haven't worked anything with Angular myself and my experience is that List.js sometimes becomes a bit superfluous when you use a framework like Angular, Ember, React etx. To the short answer is that I at the moment aren't planning to do a official solution for this problem unfortunately.
