### ISSUE TITLE
"Works both lists, tables and almost anything else. E.g. <div>,<ul>,<table>, etc."

### ISSUE THREAD

**Issue by kkerley** [javve/list.js#506]
...as long as it follows the exact same structure as the ul/li examples. Sucks to have wasted over 2 hours trying to get this to work but it's clear it won't unless what I need sorted can be presented as simply as the examples.

**Comment by javve** [comment]
Sorry that the documentation was insufficient to you. If you have any suggestions on improvements, please send them here or do a pull request.
