### ISSUE TITLE
Different classes for some list elements

### ISSUE THREAD

**Issue by ifasina** [javve/list.js#518]
Currently I only know how to apply a single class to all the items of a list (using `item: class`) but in my case I want to add a custom class depending on some other variables. Sometimes I want to add class="active" and others times class="inactive".  My current approach to doing this is:
```
$(#my-list).append('<li class=' + some code here... + '</li>')
myList = new List('my-list', options);
myList.sort("time", {order:"desc"});
```
This almost works, but because I'm also using pagination, when the element gets added weird things happen. For example, if I'm on the first page and the item gets appended, the next page is missing some items or if I'm on any other than the first and an item gets appended all pages disappear except the one I'm on.

**Comment by javve** [comment]
I see. It's a bit tricky to get that to work since List.js often rerenders the list etc, and I can't promise when the elements is kept as it is and when it's completely rerendered from scratch :/

**Comment by DaTebe** [comment]
Is it intended to continue here?
