### ISSUE TITLE
Node SSR: List js

### ISSUE THREAD

**Issue by puppetmaster3** [javve/list.js#519]
Is there .a way to get list to run in node, server side, and emit only html?

(else I'll do it w/ http://stackoverflow.com/questions/12708394/how-to-auto-bind-collection-from-html-form-using-node-js-express-framework 
and w/ https://www.npmjs.com/package/cheerio )

**Comment by javve** [comment]
Not that I'm aware of and it's not something I plan to support at the momen :/
