### ISSUE TITLE
Multiple search

### ISSUE THREAD

**Issue by CXHub** [javve/list.js#523]
Hi,

First of all, I like this great library.
I would like to know if it is possible to search for multple items, for example:

**Options:**
- Flexbox tutorial
- Flexbox playgrounds
- Frameworks
- CSS
- Awesome plugins
- HTML
- JS library

**Search:** 

`fle plu`

**Result:**
- Flexbox tutorial
- Flexbox playgrounds
- Awesome plugins

I hope what I have requested is possible,

CX

**Comment by j4kim** [comment]
Seems like you are looking for fuzzy search http://listjs.com/docs/fuzzysearch/

**Comment by javve** [comment]
Correct @j4kim! Thanks!
