### ISSUE TITLE
Table Example Broken

### ISSUE THREAD

**Issue by callumgare** [javve/list.js#529]
Hi, 
I've noticed that the table example (http://listjs.com/examples/table/) appears not to be working. Typing in the search box doesn't filter the table. I'm using Windows 10 and get the same behaviour in both the latest version of Chrome and Firefox. I also can't seem to get table filtering working in a project I'm trying to use list.js with and for that I tried both 1.4.1 and 1.5.0.
Is there something I'm missing or is this broken on the list.js end?
Cheers,
Callum.

**Comment by callumgare** [comment]
On further investigation replacing the script src in the table example with "cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js" seems to get it working. So maybe there was something broken in 1.4.1 but is fixed in 1.5.0? Sorry if this is something obvious to you guys, I've only just found this project.

**Comment by davemac** [comment]
Seems all Codepen examples are currently broken

**Comment by builtbylane** [comment]
All codepen examples are broken

**Comment by steveknoblock** [comment]
All Codpen examples are broken

**Comment by javve** [comment]
Sorry about the broken examples. They are fixed now! 😳
