### ISSUE TITLE
[Q] hide items instead of remove from dom

### ISSUE THREAD

**Issue by szachara** [javve/list.js#530]
Hi, this is really great library 💯 , I want to ask, if is possible to hide items during search, instead of remove them from dom.
I'm searching in form input's, so my input's are removed from dom now, so when I want to submit my form, I have to manually reset search `list.search('', ['name'])` before submission.

**Comment by javve** [comment]
Thanks, I'm glad you like it! 🎊 

Unfortunately is it not possible to just hide elements, I understand that it would be great in your case, however, it's much more performant to remove elements from the DOM instead of just hiding them and this is relevant for really big lists.
