### ISSUE TITLE
userList.on(updated, callback); updated not defined

### ISSUE THREAD

**Issue by jeffdbeats** [javve/list.js#538]
When I try using updated event I get ReferenceError: updated is not defined. Same thing happened when I tried filterComplete.

userList.on(updated, callback);

**Comment by rkpatel33** [comment]
+1 

This is my function call. Is there a bug here or am I using it improperly?

```
userList.on('update', function () {
  console.log('Update!')
});
```

**Comment by rkpatel33** [comment]
I figured it out, the even name should be `updated` not `update`.

**Comment by jeffdbeats** [comment]
Nice it is working now! Thanks!
