### ISSUE TITLE
List js and Masonry js conflict

### ISSUE THREAD

**Issue by pcross1986** [javve/list.js#543]
I have a 2 column list with unequal height columns. In order for them to stack, I have to use Masonry js, as I cannot use css column-count for substitution since column count lists vertically.

Since masonry uses absolute positioning, the items do not move to the top of the container while using "fuzzy search". I would think the fuzzy search works off css classes to make them display block and display none to hide, but that is not how it works. Is there anything I can do to make list js fuzzy search work properly while still using masonry js?

**Comment by javve** [comment]
I would not recommend using List.js with Masonry unfortunately and I can't say exactly how they would interact with each other, but I'm pretty confident that they won't work well together.
