### ISSUE TITLE
Counting Item After Do Fuzzy Search Not Accurate

### ISSUE THREAD

**Issue by muslimmuda15** [javve/list.js#546]
How to counting item after fuzzy search?
because in my case, I use this code 
```
var params = {
      valueNames : ['titleList', 'currentList', 'typeCode', 'categoryCode'],
      plugins: [ ListFuzzySearch() ]
}
var searchSightseeing = new List('sightseeingList', params);

$('.fuzzy-search').keyup(function(){
      var sightseeingFound = searchSightseeing.update().matchingItems.length
      console.log(sightseeingFound);
});
```

The items that have been search not same with my count.

**Comment by javve** [comment]
I'm not sure why that won't work. But I would recommend updating to List.js 1.5 where the fuzzySearch is bundled into the script instead of added as a plugin. Read more here: http://listjs.com/docs/fuzzysearch/
