### ISSUE TITLE
Exclude Table header / row from search

### ISSUE THREAD

**Issue by rhizene** [javve/list.js#547]
Hi, first, thanks for this nifty tool!

I am trying to apply this filter on a table, and I am supposed to not include the table header from being removed by the search conditions. My tagging looks like:

```
<table><tbody>
<tr><th><span class='sort' data-sort='billing_id'>Billing ID</span></th></tr>
<tr><td class='billing_id'></td></tr>
<tr><td class='billing_id'></td></tr>
</tbody></table>
```

Hoping for a reply soon

**Comment by javve** [comment]
Thanks! 
The solution would be to have the header in a thead instead. You can't exclude items from the list unfortunately.

```
<table>
<thead>
<tr><th><span class='sort' data-sort='billing_id'>Billing ID</span></th></tr>
</thead>
<tbody>
<tr><td class='billing_id'></td></tr>
<tr><td class='billing_id'></td></tr>
</tbody></table>
```
