### ISSUE TITLE
Last Page as active

### ISSUE THREAD

**Issue by DmitryS1990** [javve/list.js#548]
Is there a way to make the last page as active one from start?

**Comment by segheysens** [comment]
@DmitryS1990 I don't believe there's any functionality for setting the page in the API, but you could consider [simulating a click](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) or [sorting the data](http://listjs.com/api/#sort) in descending order if that would give a similar experience for users.

**Comment by javve** [comment]
You can use the `.show(i, page)` method right after you've initiated the list. Ref: [http://listjs.com/api/#show](http://listjs.com/api/#show)

However, I just realised that if you change the `page` size parameter from the default the pagination does not care. I'll fix that in an upcoming version.
