### ISSUE TITLE
Data Attributes Example broken on site/codepen

### ISSUE THREAD

**Issue by batmanbury** [javve/list.js#550]
Could you please put up a working example?
[http://listjs.com/examples/data-attributes-custom-attributes/](http://listjs.com/examples/data-attributes-custom-attributes/)

**Comment by segheysens** [comment]
@javve Jonny, it looks like your Codepen examples are just missing secure `https` references to the library. If you go into each, update the `script` tag for the http minified versions to the secure references in your cdn upload (`https://cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js`), they should all be working again. Once you go in and make this update, you should probably be able to close #529 #540 too.

@batmanbury In case you still need an example, I made [a fork of the Codepen with the updated script tag here](https://codepen.io/segheysens/pen/MEbELz)

**Comment by javve** [comment]
Sorry, it's fixed now!

Thanks for creating a fork of the Codepen @segheysens !
