### ISSUE TITLE
Support for complex lists

### ISSUE THREAD

**Issue by dmathisen** [javve/list.js#552]
My list is pretty complex and contains a bootstrap media object. Something like this:

```
<div id="listContainer">

<input class="search" placeholder="Search" />

<ul class="list">
  <li>

        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="..." alt="...">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Media heading</h4>
            some content
          </div>
        </div>

  </li>
</ul>

</div>
```

I'm trying to search for the `media-heading`

`var myList = new List('listContainer', ['media-heading']);`

This seems to fail - it always displays nothing when I try to filter.
Does it support complex/structured lists like this?

**Comment by javve** [comment]
The code should be like this:
```
var myList = new List('listContainer', {valueNames: ['media-heading']});
```

**Comment by dmathisen** [comment]
Ahhh. Dumb. I should pay attention. Thank you!
