### ISSUE TITLE
how to use the package with vuejs

### ISSUE THREAD

**Issue by ctf0** [javve/list.js#568]
currently i have like 4 tabs with each having its own table, so i made a watcher to track the active tab so i can reinit/reload the list, however inside the watcher i've tried both

```js
// this.table = new ListJS('table', {...})

this.table.reIndex()
this.table.update()
```

and even tried re-using the same init code 
```js
new ListJS('table', {...})
```

but non works, am i missing something ? 😢

**Comment by anselal** [comment]
@ctf0 Did yo managed to solve this?

**Comment by ctf0** [comment]
sadly no

**Comment by anselal** [comment]
check out this comment https://github.com/javve/list.js/issues/559#issuecomment-574601233

**Comment by ctf0** [comment]
the issue is with reloading the table data.

**Comment by anselal** [comment]
Where do yo retrieve the table data from ?
