### ISSUE TITLE
search is not a function

### ISSUE THREAD

**Issue by onaralili** [javve/list.js#573]
As you see above code, I defined the list also valueNames. The search input is in outside of the div.

```
var options = {
    valueNames: ['item', 'cb', 'urlIcon']
  };

  var wUrlList = new List('list_38', options);

  $(".search").keyup(function () {
    console.log(wUrlList);
    wUrlList.search($(this).val());
  });
```

When I search I get 
`TypeError: wUrlList.search is not a function`

I tried to console out to see whether it finds the list, turns out it does, however, there is no **search** function inside : 
![alt text](https://preview.ibb.co/n8mERm/Screen_Shot_2018_01_13_at_1_15_54_PM.png)

**Comment by adam-acosta** [comment]
my guess is list_38 is not an id but a class but you didn't post the html so....
