### ISSUE TITLE
Is there a way to assign a unique ID to each item in a list?

### ISSUE THREAD

**Issue by eli-oat** [javve/list.js#579]
I am wondering if there is a way to assign a unique ID to each item in a list so that I can access that specific item's value using `getElementById`?

**Comment by zorodude** [comment]
Checkout what I ended up doing at https://github.com/javve/list.js/pull/587 . I have a unique ID generated elsewhere, that I need to supply, so don't think this quite fulfills your request, but might help get you on the right track.

**Comment by javve** [comment]
In the upcoming version (2.1.0) you'll have the possibility to generate the items via a `function` and then you can generate your own unique id when you create the item. Check out this PR: https://github.com/javve/list.js/pull/634
