### ISSUE TITLE
is this project maintained anymore

### ISSUE THREAD

**Issue by mkingbe** [javve/list.js#582]
@javve hi, is this project still maintained as I see a lot of issues and pull requests and no recent commits?

**Comment by tucq88** [comment]
@javve seems still active, could you please give us answer for this ?

**Comment by javve** [comment]
Sorry about the lack of activity. List.js have been sleeping for a while but it's not dead. 

I'll do my best to make some maintenance during xmas. I appreciate your concern ❤️
