### ISSUE TITLE
Jump to desired page in pagination

### ISSUE THREAD

**Issue by viet34tqc** [javve/list.js#596]
Hi, 
I have created a product list using pagination of list.js. The product number is huge. 
So I want to create input number and a button where I can put the desired page then click the button, the page jumps to the desired number. 

Is it possible to do that?
Thank you so much!

**Comment by mcglonelevi** [comment]
I was able to do that with this:

```
var tableList = new List('tableID', options);

tableList.i = SOME NUMBER; // This is the index of the list that the page starts at.  The index starts at 1
tableList.update();  // Rerenders the list.
```

**Comment by mcglonelevi** [comment]
Also, you may want to use the `show` method.

http://listjs.com/api/#show

**Comment by viet34tqc** [comment]
It works, thank you!
