### ISSUE TITLE
Dynamically adding valueNames

### ISSUE THREAD

**Issue by sdrecker** [javve/list.js#597]
Hi there,

I want to be able to dynamically add columns to a table. Is there a way to manipulate the option 'valueNames' of an existing list or do I have to destroy it and build it new?

Thanks for any help or advise!

Greetings
Sebastian

**Comment by mcglonelevi** [comment]
I was able to do this with the following:

```
var tableList = new List('tableID', options);

tableList.valueNames = PUT YOUR ARRAY HERE;
tableList.reindex();
```

Basically, if you change tableList.valueNames, then call reindex, it changes the columns that are searched.

**Comment by sdrecker** [comment]
Unfortunately it didn't work out. I can add column for column now, but when I try to add a row after it, very strange things happen. I have to figure it out or reinit the whole list in the rare case of a column change of an existing table.

Thank you nonetheless!
