### ISSUE TITLE
[Suggestion] List.js as Vue.JS Plugin

### ISSUE THREAD

**Issue by binarykiwi** [javve/list.js#598]
Hey @javve, have you ever thought implementing a Vue.JS Plugin wrapper so that List.js can easily be used inside an Vue.JS environment? I already managed to implement some own plugins/components there, but not List.js
This would be the same direction as: #559

**Comment by javve** [comment]
Yeah, sound like it could be connected to the issue you linked to. I'll investigate and answer in that issue.
