### ISSUE TITLE
Use of list.js in custom element

### ISSUE THREAD

**Issue by sdrecker** [javve/list.js#603]
Hi folks,

I'm developing a custom element for a fully functional table. For some functionalities I use list.js. Because this plugin wasn't written with custom elements and shadow dom in mind I appended the markup for the list/table as slot of my custom element.

So my shadow dom looks like this:
```javascript
<script type="text/javascript" src="list.js"></script>
<slot></slot>
```
And my custom element like this:
```javascript
<my-table>
  <div class="list_wrapper">
    <input class="fuzzy-search" placeholder="Search" />
    <table class="table">
      <thead>
        <tr class="headers"></tr>
      </thead>
      <tbody class="list">
      </tbody>
    </table>
    <ul class="pagination"></ul>
  </div>
<my-table>
```
I add columns and rows with member functions of my custom element. The list_wrapper element itself and the options for initialization of the list/table are member variables of my custom element. I use these variables when I initiate the list /table. All of that works fine even with multiple instances of my custom element. 

But when I set pagination to true, I get following error:

> Cannot read property 'clear' of undefined

The error comes from this code in list.js
```javascript
  /*
  * Removes all items from the list
  */
  this.clear = function() {
    self.templater.clear();
    self.items = [];
    return self;
  };
```
I cannot see why self.templater is undefined. The accessibility of the list/table elements should not be affected by the parent custom element. It's no problem to get the elements of the list with document.getElementsByClassName. So the plugin should work as expected or do I overlook something?

Best Greetings

Sebastian

**Comment by javve** [comment]
Sorry about the super slow reploy. I haven't tested List.js for custom elements so I'm not sure if that could be the problem. 

I guess my answer was so late that you probably solved the problem in some other way. So I'll close the issue right now but if you're still interested in finding a solution I would like to see the code you use for initializing the list (`new List(...)`).

**Comment by cekvenich** [comment]
For custom element it is not document.getElementsByClassName
It is shadowRoot.getElementsByClassName
