### ISSUE TITLE
can't sort wordpress post titles alphanumerically?

### ISSUE THREAD

**Issue by by-erinmichelle** [javve/list.js#604]
I have a list of post titles:

- 150 Media Stream
- 2013 US Open Fan Experience
- 21 Obstacles
- 360 Weather Installation
- 440hz
- A post title
- Another post title

Wordpress sorts the titles alphanumerically so the order is the same as above^^. When sorting ASC with list.js, the order is by the _size_ of the number, not alphanumerically, and drops the titles with no spaces between numbers & letters (i.e. "440hz") to the bottom of the list:

- 21 Obstacles
- 150 Media Stream
- 360 Weather Installation
- 2013 US Open Fan Experience
- A post title
- Another post title
- 440hz

Is there a way to customize this sorting functionality to be alphanumeric? Thank you!

**Comment by javve** [comment]
List.js uses https://github.com/nwoltman/string-natural-compare for natural sorting. I recommend posting an issue there describing the problem.

You can use your own search function if you use the `listObj.sort()` method (https://listjs.com/api/#sort). However, writing a sort function is super hard, hehe.
