### ISSUE TITLE
Sort all but search only some columns

### ISSUE THREAD

**Issue by cniklas** [javve/list.js#606]
Sorry, if this topic is already dealed somewhere else, but I didn't find this described in the doku.

I have a table and want all the columns to be sorted but only _some_ of them to be _searched_.
`valueNames` seems not to differentiate between sort and search.

Any idea how to make this happen?

**Comment by javve** [comment]
You'll have to implement your own search via `listObj.search(str, columns)` (https://listjs.com/api/#search).
