### ISSUE TITLE
sort alphabetically matching the beginning of string then alphabetically for contained text

### ISSUE THREAD

**Issue by varsadadj** [javve/list.js#607]
I couldn't sorting as I need 

https://stackoverflow.com/questions/10573004/javascript-sort-alphabetically-matching-the-beginning-of-string-then-alphabetica

**Comment by javve** [comment]
List.js uses https://github.com/nwoltman/string-natural-compare for natural sorting. I recommend posting an issue there describing the problem.

You can use your own search function if you use the listObj.sort() method (https://listjs.com/api/#sort). However, writing a sort function is super hard, hehe.
