### ISSUE TITLE
Search and Filter Issue

### ISSUE THREAD

**Issue by rens-git** [javve/list.js#608]
While using the "search and filter" property sometimes the table is not filtered until certain numbers of characters are entered in the search field( for example, if the table values start with "A" or "C" or "D" or "E" or "I" or "P" or "V", the table is not sorted until "two" initial characters are entered and if they start with "L" or "S" then you need "three" characters before it is "filtered and reflected in the table".
Anyone having this issue? Anyone knows the workaround?

For the sake of demonstration, my test table (`<tbody>`) looks like this:

`"AAA","AAA","AAA","AAA","AAA","AAA","AAA","AAA","AAA"
"BBB","BBB","BBB","BBB","BBB","BBB","BBB","BBB","BBB"
"CCC","CCC","CCC","CCC","CCC","CCC","CCC","CCC","CCC"
"DDD","DDD","DDD","DDD","DDD","DDD","DDD","DDD","DDD"
"EEE","EEE","EEE","EEE","EEE","EEE","EEE","EEE","EEE"
"FFF","FFF","FFF","FFF","FFF","FFF","FFF","FFF","FFF"
"GGG","GGG","GGG","GGG","GGG","GGG","GGG","GGG","GGG"
"HHH","HHH","HHH","HHH","HHH","HHH","HHH","HHH","HHH"
"III","III","III","III","III","III","III","III","III"
"JJJ","JJJ","JJJ","JJJ","JJJ","JJJ","JJJ","JJJ","JJJ"
"KKK","KKK","KKK","KKK","KKK","KKK","KKK","KKK","KKK"
"LLL","LLL","LLL","LLL","LLL","LLL","LLL","LLL","LLL"
"MMM","MMM","MMM","MMM","MMM","MMM","MMM","MMM","MMM"
"NNN","NNN","NNN","NNN","NNN","NNN","NNN","NNN","NNN"
"OOO","OOO","OOO","OOO","OOO","OOO","OOO","OOO","OOO"
"PPP","PPP","PPP","PPP","PPP","PPP","PPP","PPP","PPP"
"QQQ","QQQ","QQQ","QQQ","QQQ","QQQ","QQQ","QQQ","QQQ"
"RRR","RRR","RRR","RRR","RRR","RRR","RRR","RRR","RRR"
"SSS","SSS","SSS","SSS","SSS","SSS","SSS","SSS","SSS"
"TTT","TTT","TTT","TTT","TTT","TTT","TTT","TTT","TTT"
"UUU","UUU","UUU","UUU","UUU","UUU","UUU","UUU","UUU"
"VVV","VVV","VVV","VVV","VVV","VVV","VVV","VVV","VVV"
"WWW","WWW","WWW","WWW","WWW","WWW","WWW","WWW","WWWW"
"XXX","XXX","XXX","XXX","XXX","XXX","XXX","XXX","XXX"
"YYY","YYY","YYY","YYY","YYY","YYY","YYY","YYY","YYY"
"ZZZ","ZZZ","ZZZ","ZZZ","ZZZ","ZZZ","ZZZ","ZZZ","ZZZ"
"111","111","111","111","111","111","111","111","111"
"222","222","222","222","222","222","222","222","222"
"333","333","333","333","333","333","333","333","333"
"444","444","444","444","444","444","444","444","444"
"555","555","555","555","555","555","555","555","555"
"666","666","666","666","666","666","666","666","666"
"777","777","777","777","777","777","777","777","777"
"888","888","888","888","888","888","888","888","888"
"999","999","999","999","999","999","999","999","999"
"000","000","000","000","000","000","000","000","000"
"1L","1L","1L","1L","1L","1L","1L","1L","1L"

"L1","L1","L1","L1","L1","L1","L1","L1","L1"
"LL1","LL1","LL1","LL1","LL1","LL1","LL1","LL1","LL1"
"1S","1S","1S","1S","1S","1S","1S","1S","1S"
"S1","S1","S1","S1","S1","S1","S1","S1","S1"
"SS1","SS1","SS1","SS1","SS1","SS1","SS1","SS1","SS1"`

**Comment by javve** [comment]
This sounds a bit like a question for [StackOverflow](https://stackoverflow.com/questions/tagged/list.js).

...and if you want me to investigate further add a Codepen or something and reopen this issue.
