### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Atulin** [javve/list.js#609]
- **117** open issues, dating back to **17 Jan 2013**
 - **23** awaiting pull requests dating back to **19 Jul 2013**
 - Last release **29 Jan 2017**
 - Last commit **21 Jun 2017**

Perhaps a fork is in order? Or adding some contributors to take care of this repo if the owner is unwilling to?

**Comment by davidlesieur** [comment]
This is a duplicate of #582.

**Comment by wowcut** [comment]
Please answer this important question.

**Comment by Atulin** [comment]
I think a lack of answer is an answer enough ¯\\\_(ツ)_/¯

**Comment by javve** [comment]
Sorry about the lack of activity. List.js have been sleeping for a while but it's not dead. 

I'll do my best to make some updates during xmas. I appreciate your concern ❤️
