### ISSUE TITLE
Wrong Example on List.js Homepage

### ISSUE THREAD

**Issue by afif-u** [javve/list.js#622]
I'm new in using List.js, so I started from the example in the homepage.
The example doesn't work.
I found an error: `new List('example-list', options, values);`
It should be `new List('users', options, values);`
![screenshot_2018-10-22 list js](https://user-images.githubusercontent.com/43276538/47300482-bf47ab00-d646-11e8-98f9-87ed6360d1e8.png)

**Comment by javve** [comment]
Oh, thanks! It's fixed now!
