### ISSUE TITLE
Attribute Style?

### ISSUE THREAD

**Issue by sellrock-de** [javve/list.js#626]
Can i add any custom style in my item array? i tried this, but this will not work.

**Comment by FrozenBeard** [comment]
Did you figure this out? im trying to set custom styles to highlight certain rows, its a bit crazy its not included

**Comment by javve** [comment]
Could you describe how you want to use this feature?

**Comment by FrozenBeard** [comment]
The best way to explain this, is if you visit https://piratemc.com/ and look at my "online players" on the right column at the bottom, you will see if any staff are online that they are highlighted another colour, also if you hover over each player they will get a bootstrap tooltip, which I will also need to pass variables into.
