### ISSUE TITLE
In search just hide elem instead of remove from DOM

### ISSUE THREAD

**Issue by babeuloula** [javve/list.js#627]
Hello, 

Is-it possible when we search or with a pagination to just hide elem instead of remove from DOM ?

I have some checkboxes, and if the user search something and click on save, only the displayed data are send to my post script.

Thanks

**Comment by anupalhub** [comment]
@babeuloula  Any update on the same?

**Comment by babeuloula** [comment]
Nop, I destroy list.js with set pagination to 10**10 before send

**Comment by javve** [comment]
Sorry, as of now you can't just hide elements. This is for performance reasons. I may update how the rendering works etc, but I unfortunately have to remove items from the DOM.

**Comment by imsheng** [comment]
@javve so can add a option that defaults to false
