### ISSUE TITLE
Multiple search

### ISSUE THREAD

**Issue by scannermobs** [javve/list.js#631]
I would very much like to do a real multiple search. At the moment I cannot implement this, so I guess it's not a feature of the plugin (which is by the way, excellent).

What I would like to be able to do is:
`myList.search('term1', ['data1'], 'term2', ['data2']);`

Unless I'm missing something, this, or something similar cannot be performed, as searches will be overridden by subsequent ones. Similar results can be achieved using filter instead, but search is more versatile in terms of its interaction with data, so being able to do this would be fantastic.

Can this be suggested as an improvement? or please let me know if there is a way to do it that I've not seen.

Cheers

**Comment by javve** [comment]
Hi @scannermobs! As you suspected is it now possible to do at the moment. But it's a pretty cool feature and I'm planning to add support for multiple searches and filters in the future. However I can't promise a date.

I'll close this issue in favour of #635 and the [Wishlist.md](https://github.com/javve/list.js/blob/master/WISHLIST.md)
