### ISSUE TITLE
Examples on home page do not work

### ISSUE THREAD

**Issue by ognjen-petrovic** [javve/list.js#643]
Hi,

Examples not working:
E.g. click on " /examples/add-get-remove/" link here https://listjs.com/examples/add-get-remove/ does nothing.
There are some errors in console:
![image](https://user-images.githubusercontent.com/3530586/51178232-44e39b80-18c2-11e9-9c21-66df3f8ae217.png)

**Comment by DanielRuf** [comment]
Mixed content due to http and https I think.

**Comment by sheffieldnick** [comment]
Yes, all the /examples/* pages need to update the http://codepen.io/... links to https://codepen.io/ or just //codepen.io/ otherwise modern browsers block that mixed http/https content from loading.

The same goes for the github buttons used on the site pages. e.g. http://ghbtns.com/...

**Comment by sheffieldnick** [comment]
All the examples can viewed directly on CodePen: https://codepen.io/javve/#

**Comment by anselal** [comment]
someone has to fix this

**Comment by cekvenich** [comment]
@anselal For me they work.

**Comment by DanielRuf** [comment]
A downvote is not very helpful. This us about the dwmo website which has mixed conten errors.

Can you see them in your browser console?

**Comment by DanielRuf** [comment]
Also protocol-less scheme `//` is an antipattern, only `https://` should be used.

**Comment by DanielRuf** [comment]
https://listjs.com/examples/add-get-remove/ can not load the codeoens at all. I wonder why this should work in your browser as this is a security relevant issue. Nothibg that you can solve without switching to https.

**Comment by DanielRuf** [comment]
https://listjs.com/examples/add-get-remove/ can not load the codepens at all. I wonder why this should work in your browser as this is a security relevant issue. Nothibg that you can solve without switching to https.

**Comment by DanielRuf** [comment]
https://listjs.com/examples/add-get-remove/ can not load the codepens at all. I wonder why this should work in your browser as this is a security relevant issue. Nothing that you can solve without switching to https.

**Comment by DanielRuf** [comment]
See https://github.com/javve/list.js/blob/master/docs/_includes/codepen.html#L7 and so on.

**Comment by anselal** [comment]
@cekvenich do the pens load in your browser?
How is that possible?

**Comment by cekvenich** [comment]
@anselal They do. On top right of my browser it shows some icon. I click the browser icon and it works. 
hth. Also bye.

**Comment by anselal** [comment]
@cekvenich no, this doesn't help

**Comment by DanielRuf** [comment]
> @anselal They do. On top right of my browser it shows some icon. I click the browser icon and it works.

Which browser exactly? I guess you explicitely allow insecure content. This is not a solution and does not work in all browsers and platforms ;-)

Anyway, we have to change something. I will provide a PR.

**Comment by DanielRuf** [comment]
See https://github.com/DanielRuf/list.js/commit/2481f2b83595a7d7fbec94af22faaa7f36371a58

I propose to create a new org and maintain a fork there as it seems that this project / repo is not actively maintained and developed anymore.

**Comment by javve** [comment]
Thanks everyone! Sorry about the super long wait. It's fixed now! 🎊
