### ISSUE TITLE
Incompatible with older Internet Explorer browsers (IE8 and below)

### ISSUE THREAD

**Issue by sheffieldnick** [javve/list.js#645]
The listjs.com/overview documentation page claims compatibility with IE6+ but v1.5.0 uses `Object.defineProperties` which was only added in IE9.

This gives javascript errors in IE6, 7 & 8 when list.js is loaded - even before it is called. The error with IE8 is
"line 1601 object doesn't support this property or method" which refers to:

`Object.defineProperties(naturalCompare, {`

A possible polyfill is provided here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties#Polyfill

**Comment by sheffieldnick** [comment]
The last release of List.js that worked on IE8 or below was 1.4.0, as Object.defineProperties is used in 1.4.1 onwards.

Is it worth officially declaring future releases of the library IE9+ (2011, 0.13% desktop market) or even IE11+ (2013, 6.33% desktop share)? it would enable a lot of old code to be removed, making the library smaller and faster. And projects that want compatibility with very old could still load 1.4.0 using IE conditional comments?

**Comment by javve** [comment]
Thanks for notifying me about this!
As of the release of v2.0.0 the support for IE6-8 is officially dropped. 

I'm thinking of moving to IE11+ as well. Maybe that'll happen soon as well. I'll make some tests and see how much that could decrease the file size etc :)

**Comment by roaster-vic** [comment]
First I want to say that this is my favorite js. lib. I said so on my linked in profile after new release.

+1 to not supporting ie11 or es5.

**Comment by javve** [comment]
Wow, I'm so happy to hear that @roaster-vic ❤️
