### ISSUE TITLE
Add options.searchColumns to List API docs

### ISSUE THREAD

**Issue by sheffieldnick** [javve/list.js#648]
Can this be added to the List API docs please?

You can use `searchColumns` in the options when you initialize the list like this:

`var options = {
  valueNames: [ 'name', 'lastname','birthdate' ],
  searchColumns:[ 'name', 'lastname' ]
};
var userList = new List('users', options);`

In this example you would have 3 fields (name, lastname, birthdate) and the search function would use only name and lastname.

_Originally posted by @pvdlg in https://github.com/javve/list.js/issues/418#issuecomment-220814149_

**Comment by javve** [comment]
Added via #696 <3
