### ISSUE TITLE
Add documentation for default CSS classes used by library?

### ISSUE THREAD

**Issue by sheffieldnick** [javve/list.js#649]
It would be really helpful to have these gathered together on a single page in the documentation. For example, it isn't obvious that the 'automagic' sort HTML elements, class="sort" turn into class="sort asc" or "sort desc" if the user clicks on them. Which is fantastic as you can define CSS like:
```
.asc::after {content:"\002B06"}
.desc::after {content:"\002B07"}
```
to display UTF-8 up/down arrows when the column is sorted.

Also include various HTML attributes that list.js uses, such as:
- `<th class="sort" data-sort="surname" data-order="desc">Surname</th>` forces the sort order to always be descending, rather than toggle between desc/asc.
- `<th class="sort" data-sort="surname" data-insensitive="false">` makes string sorting case-sensitive

**Comment by javve** [comment]
I totally agree. This is now merged into #696 . Thank you so much for adding this info 🎊
