### ISSUE TITLE
how to next/prev buttons. 

### ISSUE THREAD

**Issue by cekvenich** [javve/list.js#664]
I need to display prev button on top of list (max of 3 items show) and next button under lists.
I see some code push on it, but nothing in docs:
- https://listjs.com/docs/pagination

Ideally I have a function next()/prev() that I call in click. Help?

**Comment by cekvenich** [comment]
I found top/bottom nav css. will try

**Comment by vbbalaji** [comment]
> 
> 
> I found top/bottom nav css. will try

Can you share some links please?
