### ISSUE TITLE
vuejs - table rows disappear on sorting

### ISSUE THREAD

**Issue by anselal** [javve/list.js#677]
I use vuejs via cdn to populate a table.
When I click on a column to sort, all the rows disappear.
To debug it I hard added a row in the table and below I use v-for to populate the table.
When I try to sort all the rows disappear except the first one.
It seems like list.js caches the items before vuejs populates the table.

Is there a solution to my problem ?

**Comment by javve** [comment]
I'm sorry but my guess would be that List.js doesn't work well with Vue.js :(
