### ISSUE TITLE
Pagination does not work if your List Container does not have an ID

### ISSUE THREAD

**Issue by d4mation** [javve/list.js#685]
Pagination will result in the following error if enabled and your List Container doesn't have an ID&mdash;even if you're using an Element rather than defining the ID in the constructor.

```
Uncaught TypeError: Cannot read property 'clear' of undefined
    at t.exports.clear (app.js?ver=1586538279:1)
    at e (app.js?ver=1586538279:1)
    at app.js?ver=1586538279:1
    at Object.pagination (app.js?ver=1586538279:1)
    at Object.start (app.js?ver=1586538279:1)
    at new t.exports (app.js?ver=1586538279:1)
    at app.js?ver=1586538279:1
    at Object.<anonymous> (app.js?ver=1586538279:1)
    at e (app.js?ver=1586538279:1)
    at Object.<anonymous> (app.js?ver=1586538279:1)
```

It is difficult to tell looking at the stack trace given how I'm bundling the script, but it is complaining about line 192: 

https://github.com/javve/list.js/blob/363096e755cb60281869e5d960bbcbb748264295/src/index.js#L188-L195

**Comment by javve** [comment]
Hi! I tried to reproduce this but It seems like there is something else wrong with your code :/
https://codepen.io/javve/pen/gOMNKQP

**Comment by JerrodCarpenter** [comment]
I was able to reproduce this. @javve I did notice in your example you're using an ID with your list container, but the OP explicitly called out that not having that ID is one of the conditions of this issue.

Once I added an ID and instantiated my list with an ID and not the element, it appeared to resolved the issue for me. After some searching it looks like this is a duplicate of this issue: https://github.com/javve/list.js/issues/592

**Comment by levipadre** [comment]
I have the same error. If no id, pagination doesn't work "Uncaught TypeError: Cannot read property 'addEventListener' of null".
For example I just wanted to use data-list attribute, but I had to add and id too.
```
var list = document.querySelector('[data-list]');

var myList = new List(list, {
  valueNames: ["name", "position"],
  page: 10,
  pagination: true
});
```
So this doesn't work:
```
<div data-list>
...
</div>
```
Only this:
```
<div id="someId" data-list>
...
</div>
```

**Comment by BrandonJamesBorders** [comment]
@javve This needs to be reopened as this is still an issue.
