### ISSUE TITLE
example/pagination link not working

### ISSUE THREAD

**Issue by LE-HU** [javve/list.js#687]
Hello,
Looking for pagination library, I've just found that links inside https://listjs.com/examples/pagination/ do not redirect to desired codepen.  Tested on two browsers.
I believe it should be this one - https://codepen.io/javve/pen/bBfgD
Thank you, and take care!

**Comment by rammygit** [comment]
I believe issue is there for all the examples. https://codepen.io/javve/pen/lAmCz

**Comment by javve** [comment]
It's fixed now! 🎊
