### ISSUE TITLE
How do I get a List instance?

### ISSUE THREAD

**Issue by simzikov** [javve/list.js#688]
I am initializing List.js in a file, and I need to get its instance from a different file. Say the first file contains something like: 

```
var foo = document.getElementById('foo');
var listObj = new List(foo, {...});
```

Now I want to add some items to the list from a different file. However I don't have access to the `listObj` variable, so I need to get this List instance somehow. This is how I imaging this:

```
var foo = document.getElementById('foo');
var listObj = List.getInstance(foo).add(...);
```

So the question is if there is a a way to get a List.js instance by element? Thanks in advance.

**Comment by javve** [comment]
I'm not really sure, and this sounds more like a general JS question than a question about List.js specifically. Sorry.
