### ISSUE TITLE
I am getting error " Uncaught TypeError: Cannot read property 'childNodes' of undefined" while I am trying to read XML in my code using java script

### ISSUE THREAD

**Issue by subrahmanyamPampana** [javve/list.js#691]
<script language=JavaScript type="text/javascript"
		src="/sapui5-1.52/resources/sap-ui-core.js" id="sap-ui-bootstrap"
		data-sap-ui-libs="sap.m" data-sap-ui-bindingSyntax="complex"
		data-sap-ui-compatVersion="edge" data-sap-ui-theme="sap_belize_plus">
</script>

<script>
	var icon = new sap.ui.core.Icon({
		src : "sap-icon://globe"
	}).addStyleClass("fontIcon");
</script>

<!DOCTYPE html>
<html lang="en">

<head>
  
</head>

<body>
<div id="_LOADING_ANIMATION" style="display:none"><img src="/manufacturing/com/sap/me/system/common/client/images/loading_ani.gif"/></div>
    
    
        
        <form id="MAIN"  name="Main"  method="POST">

            <table class="pageheading" cellpadding="0" cellspacing="0" border="0"><tr><td class="toolbar_left_panel"><span style="vertical-align:middle">Count details</span></td><td class="toolbar_export_panel"></td></tr></table>

            <table class="toolbar_container">
	<tr><td class="toolbar_left_panel">
	<button id="retrieve_button" class="toolbar_button_container" onclick="#"  type="button"  title="Choose to retrieve the record" ><img class="toolbar_button_icon" src="/manufacturing/com/sap/me/system/common/client/images/icon_retrieve_on.gif"/>Retrieve</button>
	<button id="save_button" class="toolbar_button_container"  onclick="#" type="submit" title="Choose to save the current record"><img class="toolbar_button_icon" src="/manufacturing/com/sap/me/system/common/client/images/icon_save_on.gif"/>Save</button>
	<button id="clear_button" class="toolbar_button_container" type="button" title="Choose to clear the screen" onclick="#"><img class="toolbar_button_icon" src="/manufacturing/com/sap/me/system/common/client/images/icon_new_on.gif"/>Clear</button>
	</td>
	
	<td class="toolbar_right_panel">
	<button id="activity_help" class="toolbar_button_container" type="button" title="Choose to display help" ><img class="toolbar_button_icon" src="/manufacturing/com/sap/me/system/common/client/images/icon_help_on.gif"/></button></td></tr></table>

<div class="row" style="background-color:#e7e9eb;padding: 10px 0px 10px 0px";>

<table width="99%" border="0" cellpadding="4" cellspacing="0">
<tbody>
 <tr>
                    <td class="text_label" width="10%"style="font-size:15px">
                        <span class="required_field_asterisk">*</span>&nbsp;count
                    </td>
                    <td align="left" width="25%" valign="middle" nowrap="">
                        <span class="browse_container">&nbsp;
		<input id="count" type="text" name="count" size="40" maxlength="128" style="text-transform:uppercase;font-size:12px;" >
	     </span>&nbsp;
                    </td>
	<td><button type="button" class="button" style="font-size:15px"onclick="GetCount()">Get Count</button> </td>
                   
                   
                </tr>
             </tbody></table>
</div>

</div>

				
    	
 	                  
 
		

<script >

function GetCount(){
var operation=00002415-0090;
    var url = "https://"+ location.host + "/XMII/Runner?Transaction=transaction&OutputParameter=*&Content-Type=text/xml";

   
     console.log("url : "+url);
     var xhttp = new XMLHttpRequest();
     var Count;
     var CountXml
      

         xhttp.onreadystatechange = function()
		{
     			 if (xhttp.readyState == 4 && xhttp.status == 200) 
			{
     
       		 CountXml= xhttp.responseXML;
                                     
		
     console.log(CountXml);		
     Count=CountXml.getElementsByTagName("COUNT_SHOP_ORDER.PLANNED_WORK_CENTER_BO_")[0].childNodes[0].nodeValue;}
     console.log(Count);
    			

    		             //console.log(xhttp.responseText);
		
			
			
		
		} ;xhttp.open("GET", url, true);
        		 xhttp.send();
          
     document.getElementById("count").value = Count;

			 
	}	

</script> 

</div>
</body>

</html>

**Comment by rammygit** [comment]
your tbody tag should have class="list"

**Comment by javve** [comment]
Thanks for helping @rammygit !
...and next time @subrahmanyamPampana, please make sure the formatting of your question and code is better. This is pretty unreadable 😅
