### ISSUE TITLE
Support installation on node <14

### ISSUE THREAD

**Issue by aried3r** [javve/list.js#704]
Hey! I've been meaning to update to list.js 2.3 from 1.5 but in this project we're still using node 12. Would it be possible to support more node versions? Doesn't have to be 10, since that will be EOL soon, but at least 12 would be nice since it will be supported for over a year more.

This would cover [supported versions](https://nodejs.org/en/about/releases/), I believe.

```JSON
  "engines": {
    "node": "^10.0 || ^12.0 || >=14",
    "yarn": ">=1 <3"
  }
```

**Comment by javve** [comment]
Oh, this shouldn't be a problem! I'll look into it shortly!

**Comment by javve** [comment]
Thanks for notifying me about this. It was just a mistake to remove the support. So sorry about that. 

It's been corrected now: https://github.com/javve/list.js/pull/708

Please let me know it v2.3.1 works for you @aried3r

**Comment by aried3r** [comment]
Thank you! dependabot just offered the update, so I assume it is working. :)
