### ISSUE TITLE
Prevent pagination back to top

### ISSUE THREAD

**Issue by metalgigio** [javve/list.js#711]
Hi,
i just upgraded from 1.5.0 to 2.3.1.
I noticed than now when i click on a pagination's link it fires the # link so it goes to top.
There's a way to prevent it or setting a different anchor? My pagination is on a table near the footer so jumping on top is a little weird for users.
Thanks in advance

**Comment by hamburger123456** [comment]
I have got the same problem. Did you solve it?

**Comment by hamburger123456** [comment]
I patched the sources with  e.preventDefault(); 
after line events.bind(pagingList.listContainer, 'click', function (e) { ....

**Comment by Siltaar** [comment]
Another solution is to define the `item` property of the `pagination` configuration with a template that includes the id of the list. This way, when you change the current page, you scroll up to the top of the list only.

```javascript
new List('my_list', { …
    pagination: {
        item: '<li><a class="page" href="#my_list"></a></li>'
    }
});
```

**Comment by pemberton-rhan** [comment]
If anyone else comes across this issue you can just add a forward slash after the anchor to prevent it from jumping to the top.

```
new List('my_list', { …
    pagination: {
        item: '<li><a class="page" href="#/"></a></li>'
    }
});
```

**Comment by Stolzenhain** [comment]
see #727 for a more elegant solution using `<button>`

Also @metalgigio – could we close this ticket? I know one should probably adapt this with a pull request but since it seems to have worked for you, we could clean up the issue queue like this.
