### ISSUE TITLE
Programmatically change pagination

### ISSUE THREAD

**Issue by zahedkamal87** [javve/list.js#726]
Hi,
Is there no way to change the pagination later?

`var options = {`
`        valueNames: [ 'url', 'facebook', 'twitter', 'linkedin' ],`
`        page: 10,`
`        sortClass: 'datatable-btn-sort',`
`    pagination: [{`
`        name: "pagination",`
`        paginationClass: "pagination",`
`        left: 1,`
`        right: 1`
`    }]`
`};`
`var datatable = new List('urls-list', options);`

Thank you

**Comment by Hlsgs** [comment]
Checkout the properties of `datatable` in the console and identify the properties you want to alter e.g. `datatable.page`. Modify them and then call `datatable.update();`.
