### ISSUE TITLE
[Regression] Since v2.0.0 pagination buttons scroll to top of page

### ISSUE THREAD

**Issue by Hlsgs** [javve/list.js#727]
Since v2.0.0 and the move to `href="#"` for pagination buttons, the default behavior for such links takes place on click. I also think that those whould be `buttons`, not `anchors`, but that's another matter.

To get around this, I am doing this after list initialisation:
```
$list_container.find('.pagination').on('click', 'a', function(event) {
	event.preventDefault();
});
```
Not ideal, for somehting that shouldn't be there in the first place.

Also, of note, you seem to be preventing these events bubbling, so trying to be clever and doing something like this doesn't work:
```
$(document).on('click', '.pagination a', function(event) {
	event.preventDefault();
});
```

**Comment by samuelbushi** [comment]
It doesn't seem to work for me either way, keeps going to the top of the page ☹️

**Comment by Hlsgs** [comment]
> 
> 
> It doesn't seem to work for me either way, keeps going to the top of the page ☹️

Put this **after** list initialization. Replace `$list_container` with you list container and make sure pagination is under the class you filter by `.find('.pagination')`:
```
$list_container.find('.pagination').on('click', 'a', function(event) {
	event.preventDefault();
});
```

**Comment by rutger1140** [comment]
I ran into this issue as well. I'm on version `2.3.1`.

As you can see in the [pagination.js](https://github.com/javve/list.js/blob/master/src/pagination.js#L88) source there is option to set the item. It's also in [the docs](https://listjs.com/docs/pagination/).

I use it like this:
```js
const options = {
  pagination: [{
    innerWindow: 10,
    item: '<li><button class="page"></button></li>',
  }],
};
```

That should fix your issue.

**Comment by Hlsgs** [comment]
@rutger1140 Thank you so much for that info! I totally missed it, my bad! Closing.
