### ISSUE TITLE
List.js does not work on iOS Devices

### ISSUE THREAD

**Issue by arinker** [javve/list.js#733]
The following page works in all major browsers on my iMac (Chrome/firefox/Safari) but not on my iPhone:
https://www.holsteiner-verband.de/de/hengste?eigentuemer=verband&besamung=alle

Device: iPhone 12 Pro
iOS 14.4.2
Browser: Chrome/Safari

Neither the list.js search nor the filters apply.
I have checked it via Safari developer tools on my iMac, but here is not console output.
I have also updated to list.js 2.3.1 but that has no effetc.

**Comment by javve** [comment]
Hmm, but the examples at https://listjs.com does work which unfortunately makes me think there is a problem at your site :(
