### ISSUE TITLE
Search requires special node structure

### ISSUE THREAD

**Issue by joelmo** [javve/list.js#737]
The search example will break if the `p` element is removed. Elements are unable to be matched against input. See this changed example: https://codepen.io/joelmo-the-scripter/pen/BaRNGyQ

Maybe this is expected and makes implementation easier. But in certain cases this requires additional markup that's not needed otherwise.

**Comment by javve** [comment]
Yeah, the `p` element is unfortunately required at the moment, and yes, it makes the implementation easier :/
