### ISSUE TITLE
Reindex/reload items from html

### ISSUE THREAD

**Issue by jnstq** [javve/list.js#86]
It would be nice to have a function for re-index/reload the list from html. In my case the content changes via ajax.

**Comment by Soullivaneuh** [comment]
Would be great to have this features, this is the only "bad point" of your library.

If we have to refresh the page, what is the actual solution ? Re-declare a `new List` ? This will consume more and more memory isn't it?

Thanks.

**Comment by BodhiSukha** [comment]
+1

**Comment by javve** [comment]
The feature is on it's way (finally)

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by BodhiSukha** [comment]
Great!

**Comment by Soullivaneuh** [comment]
Have you a stable release for this fix?

**Comment by Soullivaneuh** [comment]
@javve At least, can you give us some indication to use this new feature?

**Comment by gambolputty** [comment]
@javve I agree with @Soullivaneuh. It would be great to have short instruction on how to use this feature. List.js is awesome (!), but the absence of this feature is giving me a hard time, when working with ajax :/

**Comment by javve** [comment]
v1.2.0 is now released and this should work now! Please tell me if not :disappointed_relieved: 
Release note: https://twitter.com/javve/status/705104547451170816 RT = :heart: :grin: 
Docs for `reIndex()`: http://www.listjs.com/docs/list-api#reindex

**Comment by dubinfo** [comment]
Thank you for reindex().

Do you have an exemple of use please ?

Thanks again.

**Comment by sylvainmetayer** [comment]
Thank you for reindex().

Is it possible to reindex pagination too ? When reindexing, it seems that only items are reindexed, not pagination. Or maybe am I using it the wrong way ?

@dubinfo Just use `myList.reindex()` assuming that myList is a list initialized before.

**Comment by jman057** [comment]
+1 for pagination refresh. When I dynamically add an item (not using the add method as I have a very large and complex object to add) all other pages are lost. I've tried all combinations of .reIndex() and .update() but nothing works. Currently I think I'll have to abandon pagination which is a shame. Great otherwise, thanks

**Comment by silver17** [comment]
Will the new update (1.2.0) be added to some Maven repository's also? The latest version there is 1.1.1. Would like to use the update() function :+1:

**Comment by tanthanhkid** [comment]
@sylvainmetayer in case u want to change the item display per page, just change page property of your list variable like "mylist.page = 10" and run mylist.update()

**Comment by cfrefah** [comment]
I would also want to update pagination when changing the option page size property. Any suggestions?

**Comment by guillaumebdx** [comment]
If you use ajax and want to reindex, you can do it to retrieve everything after the ajax call :
yourList.filter();      //reinitialise list (add all items in dom) 
yourList.reIndex(); //reinitialise index with items in dom
projectFilter();       //apply filter
//projectFilter is th name of my function who initialize variables with filters checked and selected. This function embedded :
userList.filter(function(item) {
// (...) code here with res = true/false
});

**Comment by schleimschein** [comment]
> +1 for pagination refresh. When I dynamically add an item (not using the add method as I have a very large and complex object to add) all other pages are lost. I've tried all combinations of .reIndex() and .update() but nothing works. Currently I think I'll have to abandon pagination which is a shame. Great otherwise, thanks

Is there any update on this issue? I have the same problem when I use the remove method.
