### ISSUE TITLE
Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by counterposition** [javve/list.js#9]
When attempting to create a List with no initial `<li>` elements in the DOM, List.js fails at [this line](https://github.com/javve/list/blob/49b08872f0cc9a620b277ef28d70c6ac84d642e7/src/list.js#L82).

Here is a small example (using jQuery):

```
$(function () {
    var options = {valueNames: ["name"]};
    var list = new List("list", options);

    $("#add-item").click(function () {
      list.add({name:"John"});
    });
});
```

Adding `[]` for the `values` argument of `List`'s constructor doesn't help.

Reproduced on:
Chrome 14.0.835.202
Safari 5.1.1 (7534.51.22)

**Comment by curtisblackwell** [comment]
I was having this issue, too on v1.1.1. I noticed in the examples that the ID specified when instantiating a new list always contained an element with the class `list`. Matching my code to that pattern fixed my issues.

```html
<div id="my-list">
  <!-- .list has to be within #my-list -->
  <div class="list">
    <div class="item">...</div>
    ...
  </div>
</div>
```

```js
var options = {
    valueNames: ['item'],
};

var docs = new List('my-list', options);
```

**Comment by suhaibtamimi** [comment]
just add `<ul class="list"></ul>` in the dev you selected

example:
`<div id="example-list">
                  <ul class="list"></ul>
</div>`

**Comment by suhaibtamimi** [comment]
just add `<ul class="list"></ul>` In the div that you selected

example:
`<div id="example-list">
                  <ul class="list"></ul>
</div>`

**Comment by javve** [comment]
Nah, the problem is that it needs to look like this or something:
```
<div id="my-list">
  <!-- .list has to be within #my-list -->
  <div class="list">
    <div><span class="item">...</span></div>
    ...
  </div>
</div>
```

It can't read the content when a value name class is put on the item root element.

**Comment by hallaathrad** [comment]
Shouldn't this class be configurable too?

**Comment by equatorlounge** [comment]
Has there been a native workaround for this?
I got this error message as well :(

**Comment by Leshauts** [comment]
Same, I have the same issue and get the message with last update. :/

**Comment by zeamedia** [comment]
Same with me using a `<table>` and setting `<tbody class="list">`. I have to start with an empty list/table as well but this does not work out.

**Comment by ursbraem** [comment]
List.js works very well for me. The nomenclature is a little tricky. I just note what I have to remember:

Passed directly at `List` instantiation:
- Wrapper: An ID that wraps search AND list

Passed via Options Array:
- List: A class that has items as direct children
- Search: A class for the search input
- Value: a class for each searchable region in the item. Can't be ON the item itself (this thread)

**Comment by doulosHector** [comment]
In adition to answer of @ursbraem 
If you want to use a pagination "you need to have the pagination within the List.js container." like @javve said in: [https://github.com/javve/list.js/issues/307](url)

In my case my issue was `TypeError: parent is undefined` and i resolved by add `<ul class="pagination"></ul>` in my `<div id="my-list"></div>` container.

**Comment by BeanyTheSane** [comment]
Has this issue been resolved?  I'm seeing this issue myself using 2.3.1

the table IS sortable but I'm getting this console error every time
```
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at list.min.js:1:1
    at t.exports.parse (list.min.js:1:1)
    at Object.items (list.min.js:1:1)
    at Object.start (list.min.js:1:1)
    at new t.exports (list.min.js:1:1)
    at list.min.js:1:1
    at Object.pagination (list.min.js:1:1)
    at Object.start (list.min.js:1:1)
    at new t.exports (list.min.js:1:1)
    at Object.complete (6:895:37)
```

html

```
<div id="in-process-table" data-list='{"valueNames":["status","name","value"],"pagination":false}'>
                    <div class="table-responsive scrollbar">
                        <table class="table table-hover table-striped overflow-hidden">
                            <thead class="bg-200 text-900">
                                <tr>
                                    <th scope="col" style="text-align:center;width:15%" class="sort" data-sort="status">Status</th>
                                    <th scope="col" style="text-align:left;width:50%" class="sort" data-sort="name">Name</th>
                                    <th scope="col" style="text-align:center;width:20%" class="sort" data-sort="value">Current Value</th>
                                    <th scope="col" style="text-align:center;width:15%">Details</th>
                                </tr>
                            </thead>
                            <!-- table body with rows -->
                            <tbody class="list">
                                <tr>
                                    <td class="status">
                                        <span class="badge bg-light text-success ms-2">
                                            <span class="fas fa-check-circle me-2"></span>OK
                                        </span>
                                    </td>
                                    <td class="name">
                                        name1
                                    </td>
                                    <td class="value">
                                        value1
                                    </td>
                                </tr>
                                <tr>
                                    <td class="status">
                                        <span class="badge bg-light text-success ms-2">
                                            <span class="fas fa-check-circle me-2"></span>OK
                                        </span>
                                    </td>
                                    <td class="name">
                                        secondName
                                    </td>
                                    <td class="value">
                                        secondValue
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
```

js
```
$(document).ready(function () {
    var options = {
        valueNames: ['name', 'value', 'status']
        , pagination: false
    };
    var dataTable = new List('in-process-table', options)
});
```

**Comment by D1360-64RC14** [comment]
Same error, and using table. Solved by placing an element with class `pagination` in somewhere. Example:

```html
<div class="table-responsive scrollbar">
  <table>
    <thead>
      ...
    </thead>
    <tbody class="list">
      ...
    </tbody>
  </table>
  <div>
    <ul class="pagination d-none"></ul> <!-- Here -->
  </div>
</div>
```

Used the `d-none` (bootstrap class for `display: none;`) to hide the pagination indexes.

**Comment by UVLabs** [comment]
> Same error, and using table. Solved by placing an element with class `pagination` in somewhere. Example:
> 
> ```
> <div class="table-responsive scrollbar">
>   <table>
>     <thead>
>       ...
>     </thead>
>     <tbody class="list">
>       ...
>     </tbody>
>   </table>
>   <div>
>     <ul class="pagination d-none"></ul> 
>   </div>
> </div>
> ```
> 
> Used the `d-none` (bootstrap class for `display: none;`) to hide the pagination indexes.

For me if i try to use pagination and any custom class for that pagination element, it throws the error. I have to use the default pagination class for it to not through the error when im using pagination.
