### ISSUE TITLE
Reverse order

### ISSUE THREAD

**Issue by danielsz** [javve/list.js#98]
The readme says: 

```
 2011-10-20 Beta 0.1.1 release  
 Added possibility to reverse sort the list
```

I am unclear about how to go about this. I am adding values to the list dynamically, and I would add each time a row to the top of the list, not the bottom. 

Hints regarding how to achieve that will be appreciated. 

Thanks.

**Comment by ifasina** [comment]
Hey, I tried this solution to add items to the beginning of the list but it did not work. I simply got "values.splice is not a function" is there another way to achieve this? Thank you!
